ALTER TABLE [ZGWSecurity].[Roles]
    ADD CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED ([Role_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

