ALTER TABLE [ZGWSecurity].[Function_Types]
    ADD CONSTRAINT [PK_ZGWCoreWeb_Function_Types] PRIMARY KEY CLUSTERED ([Function_Type_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

