ALTER TABLE [ZGWSecurity].[Security_Entities]
    ADD CONSTRAINT [PK_Entities] PRIMARY KEY CLUSTERED ([Security_Entity_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

