ALTER TABLE [ZGWSecurity].[Groups_Security_Entities]
    ADD CONSTRAINT [UK_ZFC_GRPS_SE] UNIQUE NONCLUSTERED ([Security_Entity_SeqID] ASC, [Group_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

