ALTER TABLE [ZGWSecurity].[Groups_Security_Entities_Functions]
    ADD CONSTRAINT [UK_ZFC_FUNCT_PER_GRPS] UNIQUE NONCLUSTERED ([Permissions_NVP_Detail_SeqID] ASC, [Groups_Security_Entities_SeqID] ASC, [Function_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

