ALTER TABLE [ZGWSecurity].[Permissions]
    ADD CONSTRAINT [PK_ZGWSecurity_Permissions] PRIMARY KEY CLUSTERED ([NVP_Detail_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

