ALTER TABLE [ZGWSecurity].[Accounts]
    ADD CONSTRAINT [PK_ZGWSecurity_Accounts] PRIMARY KEY CLUSTERED ([Account_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

