'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LineCount

    '''<summary>
    '''frmLineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmLineCount As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtExclusionPattern control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExclusionPattern As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFiles As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDirectoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDirectoryName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''litTotalLines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTotalLines As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCount As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''litLineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLineCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
