'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''AddEditBusinessUnit class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class AddEditBusinessUnit

	'''<summary>
	'''litClientMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litClientMsg As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''litBusinessUnitTranslation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litBusinessUnitTranslation As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''litBusinessUnit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litBusinessUnit As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''txtBusinessUnit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtBusinessUnit As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Requiredfieldvalidator2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Requiredfieldvalidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''txtDescription control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Requiredfieldvalidator1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Requiredfieldvalidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''txtConnectionString control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtConnectionString As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtDAL control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDAL As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''dropParent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dropParent As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''dropSkin control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dropSkin As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''STATUS_SEQ_ID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents STATUS_SEQ_ID As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtDirectory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDirectory As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''chkImpersonation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkImpersonation As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''txtAccount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAccount As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtHidPwd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtHidPwd As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
