ALTER TABLE [ZGWSecurity].[Accounts]
    ADD CONSTRAINT [UK_Accounts] UNIQUE NONCLUSTERED ([Account] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

