ALTER TABLE [ZGWSystem].[Database_Information]
    ADD CONSTRAINT [PK_ZGWSystem_Database_Information] PRIMARY KEY CLUSTERED ([Database_Information_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

