CREATE OR REPLACE
PACKAGE FOUNDATION_SECURITY AS

  /* TODO enter package declarations (types, exceptions, methods etc) here */
CREATE OR REPLACE PROCEDURE ZFP_SET_SECURITY_ENTITIES
(
  P_SE_SEQ_ID IN NUMBER DEFAULT NULL ,
  P_NAME IN VARCHAR2 DEFAULT NULL ,
  P_DESCRIPTION IN VARCHAR2 DEFAULT NULL ,
  P_URL IN VARCHAR2 DEFAULT NULL ,
  P_STATUS_SEQ_ID IN NUMBER DEFAULT NULL ,
  P_DAL IN VARCHAR2 DEFAULT NULL ,
  P_DAL_NAME IN VARCHAR2 DEFAULT NULL ,
  P_DAL_NAME_SPACE IN VARCHAR2 DEFAULT NULL ,
  P_DAL_STRING IN VARCHAR2 DEFAULT NULL ,
  P_SKIN IN CHAR DEFAULT NULL ,
  P_STYLE IN VARCHAR2 DEFAULT NULL ,
  P_ENCRYPTION_TYPE IN NUMBER DEFAULT NULL ,
  P_PARENT_SE_SEQ_ID IN NUMBER DEFAULT NULL ,
  P_PRIMARY_KEY OUT NUMBER,
  P_ErrorCode OUT NUMBER
)
AS
   v_sys_error NUMBER := 0;
BEGIN
   IF P_SE_SEQ_ID > -1 THEN
   BEGIN
      UPDATE ZF_SECURITY_ENTITIES
         SET NAME = P_NAME,
             DESCRIPTION = P_DESCRIPTION,
             URL = P_URL,
             STATUS_SEQ_ID = P_STATUS_SEQ_ID,
             DAL = P_DAL,
             DAL_NAME = P_DAL_NAME,
             DAL_NAME_SPACE = P_DAL_NAME_SPACE,
             DAL_STRING = P_DAL_STRING,
             SKIN = P_SKIN,
             STYLE = P_STYLE,
             ENCRYPTION_TYPE = P_ENCRYPTION_TYPE,
             PARENT_SE_SEQ_ID = P_PARENT_SE_SEQ_ID
         WHERE SE_SEQ_ID = P_SE_SEQ_ID;

      P_PRIMARY_KEY := P_SE_SEQ_ID;

   END;
   ELSE
   BEGIN
      -- INSERT a new row in the table.
      INSERT INTO ZF_SECURITY_ENTITIES
        ( NAME, DESCRIPTION, URL, STATUS_SEQ_ID, DAL, DAL_NAME, DAL_NAME_SPACE, DAL_STRING, SKIN, STYLE, ENCRYPTION_TYPE, PARENT_SE_SEQ_ID )
        VALUES ( P_NAME, P_DESCRIPTION, P_URL, P_STATUS_SEQ_ID, P_DAL, P_DAL_NAME, P_DAL_NAME_SPACE, P_DAL_STRING, P_SKIN, P_STYLE, P_ENCRYPTION_TYPE, P_PARENT_SE_SEQ_ID );

      -- Get the IDENTITY value for the row just inserted.
      P_PRIMARY_KEY := sqlserver_utilities.identity;

   END;
   END IF;

   -- End if
   -- Get the Error Code for the statement just executed.
   P_ErrorCode := v_sys_error;

END;

END FOUNDATION_SECURITY;