'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''GroupsGeneral class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class GroupsGeneral

	'''<summary>
	'''txtGroup_seq_id control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtGroup_seq_id As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblError control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''litGroup control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litGroup As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''txtGrpName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtGrpName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''litGroupWarning control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litGroupWarning As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''RequiredFieldValidator1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''txtGrpDescription control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtGrpDescription As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
