CREATE FUNCTION [ZFF_GET_SE_CHILDREN](@P_INCLUDE_PARENT bit, @P_SE_SEQ_ID int)
RETURNS @retFindChildren TABLE (SE_SEQ_ID int, PARENT_SE_SEQ_ID int)
AS  
BEGIN 
	IF (@P_INCLUDE_PARENT=1)
		BEGIN
			INSERT INTO @retFindChildren
			SELECT SE_SEQ_ID, PARENT_SE_SEQ_ID FROM ZFC_SECURITY_ENTITIES WHERE SE_SEQ_ID=@P_SE_SEQ_ID
 		END
		DECLARE @V_SE_SEQ_ID int, @V_PARENT_SE_SEQ_ID int

		DECLARE RetrieveChildren CURSOR STATIC LOCAL FOR
		SELECT SE_SEQ_ID,PARENT_SE_SEQ_ID FROM ZFC_SECURITY_ENTITIES WHERE PARENT_SE_SEQ_ID=@P_SE_SEQ_ID

		OPEN RetrieveChildren

		FETCH NEXT FROM RetrieveChildren
		INTO @V_SE_SEQ_ID, @V_PARENT_SE_SEQ_ID

		WHILE (@@FETCH_STATUS = 0) 
			BEGIN
				INSERT INTO @retFindChildren
				SELECT SE_SEQ_ID, PARENT_SE_SEQ_ID FROM dbo.ZFF_GET_SE_CHILDREN(0,@V_SE_SEQ_ID)
		  
				INSERT INTO @retFindChildren
				VALUES(@V_SE_SEQ_ID, @V_PARENT_SE_SEQ_ID)
		   
				FETCH NEXT FROM RetrieveChildren
				INTO @V_SE_SEQ_ID, @V_PARENT_SE_SEQ_ID
			END
		-- END WHILE
		CLOSE RetrieveChildren
		DEALLOCATE RetrieveChildren

		RETURN
END
