'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''StatesYears class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class StatesYears

	'''<summary>
	'''pnlAddYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlAddYear As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtNewYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNewYear As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtNewConnectionString control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNewConnectionString As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''txtCurrentYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCurrentYear As Global.System.Web.UI.WebControls.TextBox
End Class
