'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''StatesGeneral class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class StatesGeneral

	'''<summary>
	'''litState control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litState As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''txtDescription control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Requiredfieldvalidator1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Requiredfieldvalidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''STATUS_SEQ_ID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents STATUS_SEQ_ID As Global.System.Web.UI.WebControls.DropDownList
End Class
