CREATE TABLE [ZGWSecurity].[Functions] (
    [Function_SeqID]                    INT                  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Action]                            VARCHAR (256)        NOT NULL,
    [Added_By]                          INT                  NOT NULL,
    [Added_Date]                        DATETIME             CONSTRAINT [DF_ZGWSecurity_Functions_ADDED_DATE] DEFAULT (getdate()) NOT NULL,
	[Controller]                        VARCHAR (512) SPARSE NULL,
    [Description]                       VARCHAR (512)        NOT NULL,
    [Enable_Notifications]              INT                  CONSTRAINT [DF_ZGWSecurity_Functions_ENABLE_NOTIFICATIONS] DEFAULT ((0)) NOT NULL,
    [Enable_View_State]                 INT                  NOT NULL,
    [Function_Type_SeqID]               INT                  NULL,
    [Is_Nav]                            INT                  NOT NULL,
    [Link_Behavior]                     INT                  NOT NULL,
    [Meta_Key_Words]                    VARCHAR (512) SPARSE NULL,
    [Name]                              VARCHAR (30)         NOT NULL,
    [Navigation_Types_NVP_Detail_SeqID] INT                  NOT NULL,
    [Notes]                             VARCHAR (512) SPARSE NULL,
    [No_UI]                             INT                  CONSTRAINT [DF_ZGWSecurity_Functions_NO_UI] DEFAULT ((0)) NOT NULL,
    [Parent_SeqID]                      INT                  NULL,
    [Redirect_On_Timeout]               INT                  CONSTRAINT [DF_ZGWSecurity_Functions_REDIRECT_ON_TIMEOUT] DEFAULT ((1)) NOT NULL,
	[Resolve]	                        VARCHAR (MAX) SPARSE NULL,
    [Sort_Order]                        INT                  CONSTRAINT [DF_ZGWSecurity_Functions_Sort_Order] DEFAULT ((0)) NOT NULL,
    [Source]                            VARCHAR (512) SPARSE NULL,
    [Updated_By]                        INT                  NULL,
    [Updated_Date]                      DATETIME             NULL,
    CONSTRAINT [PK_Functions] PRIMARY KEY CLUSTERED ([Function_SeqID] ASC),
    CONSTRAINT [FK_Functions_Function_Types] FOREIGN KEY ([Function_Type_SeqID]) REFERENCES [ZGWSecurity].[Function_Types] ([Function_Type_SeqID]),
    CONSTRAINT [FK_Functions_Functions] FOREIGN KEY ([Parent_SeqID]) REFERENCES [ZGWSecurity].[Functions] ([Function_SeqID]),
    CONSTRAINT [FK_Functions_Navigation_Types] FOREIGN KEY ([Navigation_Types_NVP_Detail_SeqID]) REFERENCES [ZGWSecurity].[Navigation_Types] ([NVP_Detail_SeqID]),
    CONSTRAINT [UK_ZGWSecurity_Functions] UNIQUE NONCLUSTERED ([Action] ASC)
);

