'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''FileManagerControl class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class FileManagerControl

	'''<summary>
	'''litErrorMSG control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litErrorMSG As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''currentDirectory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents currentDirectory As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblClientMSG control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblClientMSG As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''firstRow control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents firstRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''btnDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''cmdSelect control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmdSelect As Global.System.Web.UI.HtmlControls.HtmlInputButton

	'''<summary>
	'''btnGoUp control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnGoUp As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''litUploadFile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litUploadFile As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''txtFileToUpload control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFileToUpload As Global.System.Web.UI.HtmlControls.HtmlInputFile

	'''<summary>
	'''btnUpLoad control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnUpLoad As Global.System.Web.UI.HtmlControls.HtmlInputButton

	'''<summary>
	'''CreateNewDirectory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CreateNewDirectory As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''txtNewDirectory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNewDirectory As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnNewDirectory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnNewDirectory As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''DGFileSystem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DGFileSystem As Global.System.Web.UI.WebControls.DataGrid

	'''<summary>
	'''literalPath control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents literalPath As Global.System.Web.UI.WebControls.Label
End Class
