//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowthWare.WebApplication.UserControls {
    
    
    public partial class GroupControl {
        
        /// <summary>
        /// ctlViewGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GrowthWare.WebSupport.CustomWebControls.ListPicker ctlViewGroups;
        
        /// <summary>
        /// ctlAddGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GrowthWare.WebSupport.CustomWebControls.ListPicker ctlAddGroups;
        
        /// <summary>
        /// ctlEditGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GrowthWare.WebSupport.CustomWebControls.ListPicker ctlEditGroups;
        
        /// <summary>
        /// ctlDeleteGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GrowthWare.WebSupport.CustomWebControls.ListPicker ctlDeleteGroups;
    }
}
