'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FileManagerControl

    '''<summary>
    '''litErrorMSG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litErrorMSG As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''directorySelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents directorySelector As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientMSG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientMSG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''firstRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''UploadControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadControl As Global.System.Web.UI.UserControl

    '''<summary>
    '''tdNewDirectory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdNewDirectory As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CreateNewDirectory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateNewDirectory As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtNewDirectory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewDirectory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SearchControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchControl As Global.GrowthWare.WebApplication.Search

    '''<summary>
    '''literalPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents literalPath As Global.System.Web.UI.WebControls.Label
End Class
