'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GroupControl

    '''<summary>
    '''ctlViewGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlViewGroups As Global.GrowthWare.WebSupport.CustomWebControls.ListPicker

    '''<summary>
    '''ctlAddGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlAddGroups As Global.GrowthWare.WebSupport.CustomWebControls.ListPicker

    '''<summary>
    '''ctlEditGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlEditGroups As Global.GrowthWare.WebSupport.CustomWebControls.ListPicker

    '''<summary>
    '''ctlDeleteGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDeleteGroups As Global.GrowthWare.WebSupport.CustomWebControls.ListPicker
End Class
