'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RolesControl

    '''<summary>
    '''ctlViewRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlViewRoles As Global.GrowthWare.WebSupport.CustomWebControls.ListPicker

    '''<summary>
    '''ctlAddRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlAddRoles As Global.GrowthWare.WebSupport.CustomWebControls.ListPicker

    '''<summary>
    '''ctlEditRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlEditRoles As Global.GrowthWare.WebSupport.CustomWebControls.ListPicker

    '''<summary>
    '''ctlDeleteRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDeleteRoles As Global.GrowthWare.WebSupport.CustomWebControls.ListPicker
End Class
