'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DisplayError

	'''<summary>
	'''lblBUName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBUName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblComputer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblComputer As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblAccount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAccount As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblOpSystem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblOpSystem As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblBrowser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBrowser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lbltoday control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbltoday As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblErrSource control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErrSource As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblErrMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErrMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblErrorlog control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErrorlog As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblErrMsg1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErrMsg1 As Global.System.Web.UI.WebControls.Label
End Class
