CREATE PROCEDURE [dbo].[ZFP_GET_NVP_DETAILS]
	@P_NVP_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
AS
	/*
This not the most effecient however this should
not be called very often ... it is intended for the
front end to cache the information and only get called
when needed
	*/
	CREATE TABLE #NVP_DETAILS (NVP_SEQ_DET_ID INT, NVP_SEQ_ID INT, NVP_DET_VALUE VARCHAR(50), NVP_DET_TEXT VARCHAR(300), STATUS_SEQ_ID INT, SORT_ORDER INT, ADDED_BY INT, ADDED_DATE DATETIME, UPDATED_BY INT, UPDATED_DATE DATETIME) 
	DECLARE @V_NVP_SEQ_ID INT
	DECLARE @V_STATIC_NAME VARCHAR(30)
	DECLARE @V_Statement nvarchar(4000)
	SET @V_Statement = 'SELECT * FROM '
	DECLARE V_ZFC_NVP CURSOR STATIC LOCAL FOR
		SELECT
			NVP_SEQ_ID,
			STATIC_NAME
		FROM
			ZFC_NVP

	OPEN V_ZFC_NVP
		FETCH NEXT FROM V_ZFC_NVP
		INTO 
			@V_NVP_SEQ_ID,  
			@V_STATIC_NAME
		WHILE (@@FETCH_STATUS = 0)
			BEGIN
				SET @V_Statement =  @V_Statement + CONVERT(VARCHAR,@V_STATIC_NAME) + ' UNION ALL SELECT * FROM '
				FETCH NEXT FROM V_ZFC_NVP INTO @V_NVP_SEQ_ID, @V_STATIC_NAME
			END
	CLOSE V_ZFC_NVP
	DEALLOCATE V_ZFC_NVP
	SET @V_Statement = SUBSTRING(@V_Statement, 0, LEN(@V_Statement) - 19)
	PRINT @V_Statement
	INSERT INTO #NVP_DETAILS EXECUTE dbo.sp_executesql @V_Statement = @V_Statement

	IF @P_NVP_SEQ_ID = -1
		SELECT 
			#NVP_DETAILS.NVP_SEQ_DET_ID,
			#NVP_DETAILS.NVP_SEQ_ID,
			ZFC_NVP.STATIC_NAME,
			#NVP_DETAILS.NVP_DET_VALUE, 
			#NVP_DETAILS.NVP_DET_TEXT, 
			#NVP_DETAILS.STATUS_SEQ_ID, 
			#NVP_DETAILS.SORT_ORDER, 
			#NVP_DETAILS.ADDED_BY, 
			#NVP_DETAILS.ADDED_DATE, 
			#NVP_DETAILS.UPDATED_BY, 
			#NVP_DETAILS.UPDATED_DATE 
		FROM 
			#NVP_DETAILS,
			ZFC_NVP
		WHERE
			#NVP_DETAILS.NVP_SEQ_ID = ZFC_NVP.NVP_SEQ_ID
		ORDER BY
			ZFC_NVP.STATIC_NAME,
			#NVP_DETAILS.NVP_DET_TEXT
	ELSE
		SELECT 
			#NVP_DETAILS.NVP_SEQ_DET_ID,
			#NVP_DETAILS.NVP_SEQ_ID,
			ZFC_NVP.STATIC_NAME,
			#NVP_DETAILS.NVP_DET_VALUE, 
			#NVP_DETAILS.NVP_DET_TEXT, 
			#NVP_DETAILS.STATUS_SEQ_ID, 
			#NVP_DETAILS.SORT_ORDER, 
			#NVP_DETAILS.ADDED_BY, 
			#NVP_DETAILS.ADDED_DATE, 
			#NVP_DETAILS.UPDATED_BY, 
			#NVP_DETAILS.UPDATED_DATE 
		FROM 
			#NVP_DETAILS,
			ZFC_NVP
		WHERE
			#NVP_DETAILS.NVP_SEQ_ID = ZFC_NVP.NVP_SEQ_ID
			AND ZFC_NVP.NVP_SEQ_ID = @P_NVP_SEQ_ID
		ORDER BY
			ZFC_NVP.STATIC_NAME,
			#NVP_DETAILS.NVP_DET_TEXT

	DROP TABLE #NVP_DETAILS

-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
