
CREATE PROCEDURE [ZFP_DEL_GROUP_ROLES] (
	@P_GROUP_SEQ_ID INT,
	@P_SE_SEQ_ID INT,
	@P_ADD_UP_BY	INT
)
AS
	DELETE
		ZFC_SECURITY_GRPS_RLS
	WHERE
		GRPS_SE_SEQ_ID IN (SELECT GRPS_SE_SEQ_ID 
					FROM ZFC_SECURITY_GRPS_SE 
					WHERE SE_SEQ_ID=@P_SE_SEQ_ID
					AND GROUP_SEQ_ID = @P_GROUP_SEQ_ID)

