CREATE PROCEDURE [ZFP_SET_STATE](
	@P_STATE VARCHAR(2),
	@P_DESCRIPTION VARCHAR(128),
	@P_STATUS_SEQ_ID INT,
	@P_UPDATED_BY INT,
	@P_UPDATED_DATE DATETIME,
	@P_PRIMARY_KEY VARCHAR(2) OUTPUT,
	@P_ErrorCode int OUTPUT
) AS
BEGIN
	UPDATE
		ZOP_STATES
	SET 
		[STATE] = @P_STATE,
		[DESCRIPTION] = @P_DESCRIPTION,
		STATUS_SEQ_ID = @P_STATUS_SEQ_ID,
		UPDATED_BY = @P_UPDATED_BY,
		UPDATED_DATE = @P_UPDATED_DATE
	WHERE
		[STATE] = @P_STATE

	SELECT @P_PRIMARY_KEY = @P_STATE
END
-- Get the Error Code for the statement just executed.
	SELECT @P_ErrorCode=@@ERROR
