CREATE PROCEDURE [ZFP_GET_DIRECTORY](
	@P_FUNCTION_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
) AS
IF @P_FUNCTION_SEQ_ID = -1
	BEGIN
		SELECT
			FUNCTION_SEQ_ID,
			DIRECTORY,
			IMPERSONATE,
			IMPERSONATE_ACCOUNT,
			IMPERSONATE_PWD,
			ADDED_BY,
			ADDED_DATE,
			UPDATED_BY,
			UPDATED_DATE
		FROM
			ZFO_DIRECTORIES
	END
ELSE
	BEGIN
		SELECT
			FUNCTION_SEQ_ID,
			DIRECTORY,
			IMPERSONATE,
			IMPERSONATE_ACCOUNT,
			IMPERSONATE_PWD,
			ADDED_BY,
			ADDED_DATE,
			UPDATED_BY,
			UPDATED_DATE
		FROM
			ZFO_DIRECTORIES
		WHERE
			FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID
	END
-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
