CREATE PROCEDURE [ZFP_GET_FUNCTION_SORT] (
	@P_FUNCTION_SEQ_ID INT,
	@P_ErrorCode int OUTPUT

) AS
	DECLARE @V_PARENT_ID INT
	DECLARE @V_NAV_TYPE_ID INT
	SET @V_PARENT_ID = (SELECT PARENT_FUNCTION_SEQ_ID FROM ZFC_FUNCTIONS WHERE FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID)
	SET @V_NAV_TYPE_ID = (SELECT NAVIGATION_NVP_SEQ_DET_ID FROM ZFC_FUNCTIONS WHERE FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID)
	SELECT
		FUNCTION_SEQ_ID,
		[NAME],
		[ACTION],
		SORT_ORDER
	FROM
		ZFC_FUNCTIONS
	WHERE
		PARENT_FUNCTION_SEQ_ID = @V_PARENT_ID
		AND IS_NAV = 1
		AND NAVIGATION_NVP_SEQ_DET_ID = @V_NAV_TYPE_ID
	ORDER BY
		SORT_ORDER ASC
