CREATE PROCEDURE [ZFP_GET_FUNCTIONS_SECURITY]
	@P_SE_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
AS
	DECLARE @V_AvalibleItems TABLE (FUNCTION_SEQ_ID INT, PERMISSIONS_SEQ_ID INT, ROLE VARCHAR(50))
	INSERT INTO @V_AvalibleItems
	SELECT DISTINCT -- Directly assigned roles
		[FUNCTIONS].FUNCTION_SEQ_ID,
		[PERMISSIONS].NVP_SEQ_DET_ID,
		ROLES.[NAME] AS ROLE
	FROM
		ZFC_SECURITY_RLS_SE SE_ROLES,
		ZFC_SECURITY_RLS ROLES,
		ZFC_SECURITY_FUNCT_RLS SECURITY,
		ZFC_FUNCTIONS [FUNCTIONS],
		ZFC_PERMISSIONS [PERMISSIONS]
	WHERE
		SE_ROLES.ROLE_SEQ_ID = ROLES.ROLE_SEQ_ID
		AND SECURITY.RLS_SE_SEQ_ID = SE_ROLES.RLS_SE_SEQ_ID
		AND SECURITY.FUNCTION_SEQ_ID = [FUNCTIONS].FUNCTION_SEQ_ID
		AND [PERMISSIONS].NVP_SEQ_DET_ID = SECURITY.PERMISSIONS_NVP_SEQ_DET_ID
		AND SE_ROLES.SE_SEQ_ID IN (SELECT SE_SEQ_ID FROM dbo.ZFF_GET_SE_PARENTS(1,@P_SE_SEQ_ID))
	UNION
	SELECT DISTINCT -- Roles assigned via groups
		[FUNCTIONS].FUNCTION_SEQ_ID,
		[PERMISSIONS].NVP_SEQ_DET_ID,
		ROLES.[NAME] AS ROLE
	FROM
		ZFC_SECURITY_FUNCT_GRPS,
		ZFC_SECURITY_GRPS_SE,
		ZFC_SECURITY_GRPS_RLS,
		ZFC_SECURITY_RLS_SE,
		ZFC_SECURITY_RLS ROLES,
		ZFC_FUNCTIONS [FUNCTIONS],
		ZFC_PERMISSIONS [PERMISSIONS]
	WHERE
		ZFC_SECURITY_FUNCT_GRPS.FUNCTION_SEQ_ID = [FUNCTIONS].FUNCTION_SEQ_ID
		AND ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID = ZFC_SECURITY_FUNCT_GRPS.GRPS_SE_SEQ_ID
		AND ZFC_SECURITY_GRPS_RLS.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID
		AND ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID = ZFC_SECURITY_GRPS_RLS.RLS_SE_SEQ_ID
		AND ROLES.ROLE_SEQ_ID = ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID
		AND [PERMISSIONS].NVP_SEQ_DET_ID = ZFC_SECURITY_FUNCT_GRPS.PERMISSIONS_NVP_SEQ_DET_ID
		AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID IN (SELECT SE_SEQ_ID FROM dbo.ZFF_GET_SE_PARENTS(1,@P_SE_SEQ_ID))

	IF (SELECT COUNT(FUNCTION_SEQ_ID) FROM @V_AvalibleItems) > 0
		BEGIN
			SELECT * FROM @V_AvalibleItems
			-- Get the Error Code for the statement just executed.
			SELECT @P_ErrorCode=@@ERROR
		END
	ELSE
		BEGIN
			UPDATE ZFC_SECURITY_ENTITIES
				SET 
					PARENT_SE_SEQ_ID = dbo.ZFF_GET_DEFAULT_Security_Entity_ID()
				WHERE
					SE_SEQ_ID = @P_SE_SEQ_ID
			EXEC ZFP_GET_FUNCTIONS_SECURITY @P_SE_SEQ_ID, NULL
			SELECT @P_ErrorCode=1
		END
