CREATE PROCEDURE [ZFP_GET_VALID_SES]
	@P_ACCT VARCHAR(50),
	@P_IS_SE_ADMIN INT,
	@P_SE_SEQ_ID AS INT,
	@P_ErrorCode int OUTPUT
AS
SET NOCOUNT ON
	DECLARE @V_ACTIVE_STATUS VARCHAR(50)
	DECLARE @T_VALID_SE TABLE (SE_SEQ_ID INT)
	DECLARE @V_IS_SYS_ADMIN INT
	SET @V_ACTIVE_STATUS = (SELECT [STATUS_SEQ_ID] FROM ZFC_SYSTEM_STATUS WHERE UPPER([DESCRIPTION]) = 'ACTIVE')
	SET @V_IS_SYS_ADMIN = (SELECT IS_SYSTEM_ADMIN FROM ZFC_ACCTS WHERE UPPER(ACCT) = UPPER(@P_ACCT))
	IF @V_IS_SYS_ADMIN = 0
		BEGIN
			INSERT INTO @T_VALID_SE
				SELECT -- Security Entitys via roles
					ZFC_SECURITY_RLS_SE.SE_SEQ_ID
				FROM
					ZFC_ACCTS,
					ZFC_SECURITY_ACCTS_RLS,
					ZFC_SECURITY_RLS_SE,
					ZFC_SECURITY_RLS
				WHERE
					ZFC_ACCTS.ACCT = @P_ACCT
					AND ZFC_SECURITY_ACCTS_RLS.ACCT_SEQ_ID = ZFC_ACCTS.ACCT_SEQ_ID
					AND ZFC_SECURITY_ACCTS_RLS.RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
					AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
					AND ZFC_SECURITY_RLS.IS_SYSTEM_ONLY = 0
				UNION
				SELECT -- Security Entitys via groups
					ZFC_SECURITY_RLS_SE.SE_SEQ_ID
				FROM
					ZFC_ACCTS,
					ZFC_SECURITY_ACCTS_GRPS,
					ZFC_SECURITY_GRPS_SE,
					ZFC_SECURITY_GRPS_RLS,
					ZFC_SECURITY_RLS_SE,
					ZFC_SECURITY_RLS
				WHERE
					ZFC_ACCTS.ACCT = @P_ACCT
					AND ZFC_SECURITY_ACCTS_GRPS.ACCT_SEQ_ID = ZFC_ACCTS.ACCT_SEQ_ID
					AND ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_RLS.GRPS_SE_SEQ_ID
					AND ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID = ZFC_SECURITY_GRPS_RLS.RLS_SE_SEQ_ID
					AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
				IF @P_IS_SE_ADMIN = 0 -- FALSE
					BEGIN
						SELECT
							SE_SEQ_ID,
							[NAME],
							[DESCRIPTION]
						FROM
							ZFC_SECURITY_ENTITIES
						WHERE
							ZFC_SECURITY_ENTITIES.SE_SEQ_ID IN (SELECT * FROM @T_VALID_SE)
							AND ZFC_SECURITY_ENTITIES.STATUS_SEQ_ID = @V_ACTIVE_STATUS
					END
				ELSE
					BEGIN
						SELECT
							SE_SEQ_ID,
							[NAME],
							[DESCRIPTION]
						FROM
							ZFC_SECURITY_ENTITIES
						WHERE
							ZFC_SECURITY_ENTITIES.SE_SEQ_ID IN (SELECT * FROM @T_VALID_SE)
							OR ZFC_SECURITY_ENTITIES.PARENT_SE_SEQ_ID = @P_SE_SEQ_ID
					END
				-- END IF
		END
	ELSE
		BEGIN
			SELECT
				SE_SEQ_ID,
				[NAME],
				[DESCRIPTION]
			FROM
				ZFC_SECURITY_ENTITIES
		END

-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
