
CREATE PROCEDURE [ZFP_SET_GROUP_RLS] (
	@P_GROUP_SEQ_ID INT,
	@P_SE_SEQ_ID INT,
	@P_ROLES NVARCHAR(1000),
	@P_ADD_UP_BY    INT,
	@P_ErrorCode int OUTPUT
)
AS
	SET NOCOUNT ON
	DECLARE @V_RLS_SE_SEQ_ID 		INT,
		@V_ROLE_NAME		VARCHAR(50),
		@V_IS_SYSTEM 		INT,
		@V_POS 			INT,
		@V_GRPS_SE_SEQ_ID INT
		--NEED TO DELETE EXISTING ROLES ASSOCITAED BEFORE 
		-- INSERTING NEW ONES. EXECUTION OF THIS STORED PROC
		-- IS MOVED FROM CODE			
		EXEC ZFP_DEL_GROUP_ROLES @P_GROUP_SEQ_ID,@P_SE_SEQ_ID,@P_ADD_UP_BY	
		SET @P_ROLES = LTRIM(RTRIM(@P_ROLES))+ ','
		SET @V_POS = CHARINDEX(',', @P_ROLES, 1)
	
		IF REPLACE(@P_ROLES, ',', '') <> ''
		BEGIN
			WHILE @V_POS > 0
			BEGIN
				SET @V_ROLE_NAME = LTRIM(RTRIM(LEFT(@P_ROLES, @V_POS - 1)))
				IF @V_ROLE_NAME <> ''
				--print @V_ROLE_NAME -- DEBUG
				BEGIN
					--SELECT THE ROLE_SEQ_ID FROM THE ROLES
					--TABLE FOR ALL THE ROLES PASSED
					SELECT  
						@V_RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
					FROM
					 	ZFC_SECURITY_RLS_SE
					WHERE 
						ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = (SELECT ROLE_SEQ_ID FROM ZFC_SECURITY_RLS WHERE ZFC_SECURITY_RLS.[NAME] = @V_ROLE_NAME)
						AND ZFC_SECURITY_RLS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
					-- print @V_RLS_SE_SEQ_ID -- DEBUG

					SELECT
						@V_GRPS_SE_SEQ_ID = GRPS_SE_SEQ_ID
					FROM
						ZFC_SECURITY_GRPS_SE
					WHERE
						SE_SEQ_ID = @P_SE_SEQ_ID
						AND GROUP_SEQ_ID = @P_GROUP_SEQ_ID
					
					--print @V_GRPS_SE_SEQ_ID -- DEBUG
					/*
					INSERT THE ZFC_SECURITY_GRPS_RLS
					WITH ROLES INFORMATION
					*/	
					IF @V_RLS_SE_SEQ_ID IS NOT NULL
					BEGIN
									
						INSERT ZFC_SECURITY_GRPS_RLS (
							RLS_SE_SEQ_ID,
							GRPS_SE_SEQ_ID,
							ADDED_BY,
							ADDED_DATE
						)VALUES(
							@V_RLS_SE_SEQ_ID,
							@V_GRPS_SE_SEQ_ID,
							@P_ADD_UP_BY,
							GETDATE()
						)
				
						--PRINT '*****************INSERTED INTO ZFC_SECURITY_GRPS_RLS'
					END
	
				END
				SET @P_ROLES = RIGHT(@P_ROLES, LEN(@P_ROLES) - @V_POS)
				SET @V_POS = CHARINDEX(',', @P_ROLES, 1)
	
			END
		END	
	SELECT @P_ErrorCode = @@error
