CREATE PROCEDURE [ZFP_SET_FUNCTION_RLS](
	@P_FUNCTION_SEQ_ID INT,
	@P_SE_SEQ_ID INT,
	@P_ROLES VARCHAR(1000),
	@P_PERMISSIONS_SEQ_ID INT,
	@P_ADDUPD_BY INT,
	@P_ErrorCode int OUTPUT
)
 AS
BEGIN TRAN
	-- NEED TO DELETE EXISTING ROLE ASSOCITAED WITH THE FUNCTION BEFORE 
	-- INSERTING NEW ONES.
	EXEC ZFP_DEL_FUNCTION_RL_SECURITY @P_FUNCTION_SEQ_ID,@P_SE_SEQ_ID,@P_PERMISSIONS_SEQ_ID,@P_ADDUPD_BY,@P_ErrorCode
	DECLARE @V_ROLE_SEQ_ID 		AS 	INT
	DECLARE @V_SE_RLS_SECURITY_ID 	AS 	INT
	DECLARE @V_ROLE_NAME		AS	VARCHAR(50)
	DECLARE @V_Pos 			AS	INT
	SET @P_ROLES = LTRIM(RTRIM(@P_ROLES))+ ','
	SET @V_Pos = CHARINDEX(',', @P_ROLES, 1)
	IF REPLACE(@P_ROLES, ',', '') <> ''
		WHILE @V_Pos > 0
		BEGIN
			SET @V_ROLE_NAME = LTRIM(RTRIM(LEFT(@P_ROLES, @V_Pos - 1)))
			IF @V_ROLE_NAME <> ''
			BEGIN
				--select the role seq id first
				SELECT @V_ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID 
				FROM ZFC_SECURITY_RLS 
				WHERE [NAME]=@V_ROLE_NAME

 				SELECT
					@V_SE_RLS_SECURITY_ID=RLS_SE_SEQ_ID
				FROM
					ZFC_SECURITY_RLS_SE
				WHERE
					ROLE_SEQ_ID = @V_ROLE_SEQ_ID AND
					SE_SEQ_ID = @P_SE_SEQ_ID
					--PRINT('@V_SE_RLS_SECURITY_ID = ' + CONVERT(VARCHAR,@V_SE_RLS_SECURITY_ID))
				IF NOT EXISTS(
						SELECT 
							RLS_SE_SEQ_ID 
						FROM 
							ZFC_SECURITY_FUNCT_RLS 
						WHERE 
						FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID 
						AND PERMISSIONS_NVP_SEQ_DET_ID = @P_PERMISSIONS_SEQ_ID
						AND RLS_SE_SEQ_ID = @V_SE_RLS_SECURITY_ID
				)
				BEGIN
					--PRINT('INSERT RECORD')
					INSERT ZFC_SECURITY_FUNCT_RLS (
						FUNCTION_SEQ_ID,
						RLS_SE_SEQ_ID,
						PERMISSIONS_NVP_SEQ_DET_ID,
						ADDED_BY
					)
					VALUES (
						@P_FUNCTION_SEQ_ID,
						@V_SE_RLS_SECURITY_ID,
						@P_PERMISSIONS_SEQ_ID,
						@P_ADDUPD_BY
					)
				END
		
			END
				SET @P_ROLES = RIGHT(@P_ROLES, LEN(@P_ROLES) - @V_Pos)
				SET @V_Pos = CHARINDEX(',', @P_ROLES, 1)
			SELECT @P_ErrorCode = @@error
		END
	SELECT @P_ErrorCode = @@error
	IF @P_ErrorCode <> 0 GOTO ABEND
COMMIT TRAN
	ABEND:
IF @P_ErrorCode <> 0
	BEGIN
		PRINT 'Yikes!'
		ROLLBACK TRAN
	END
