CREATE PROCEDURE [ZFP_GET_NOTIFICATION_STATUS] 
(
	@P_SE_SEQ_ID int,
	@P_FUNCTION_SEQ_ID int,
	@P_ACCOUNT VARCHAR(128),
	@P_PRIMARY_KEY INT OUTPUT
)
AS
-- GET ACCT_SEQ_ID
DECLARE @V_ACCT_SEQ_ID Int
SET @V_ACCT_SEQ_ID = (SELECT ACCT_SEQ_ID FROM ZFC_ACCTS WHERE ACCT = @P_ACCOUNT)

IF EXISTS
  (
	SELECT 
		ADDED_BY
	FROM 
		ZFC_NOTIFICATIONS
	WHERE 
		SE_SEQ_ID = @P_SE_SEQ_ID
		AND FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID
		AND ADDED_BY = @V_ACCT_SEQ_ID
  )
  SELECT @P_PRIMARY_KEY = 1
ELSE
  SELECT @P_PRIMARY_KEY = 0
