CREATE PROCEDURE [ZFP_DEL_NVP_RL_SECURITY](
	@P_NVP_SEQ_ID		INT,
	@P_SE_SEQ_ID			INT,
	@P_PERMISSIONS_SEQ_ID	INT,
	@P_ADDUPD_BY		INT,
	@P_ErrorCode 		INT OUTPUT
)
 AS
BEGIN
	DELETE FROM 
		ZFC_SECURITY_NVP_RLS 
	WHERE 
		RLS_SE_SEQ_ID IN(SELECT RLS_SE_SEQ_ID FROM ZFC_SECURITY_RLS_SE WHERE SE_SEQ_ID = @P_SE_SEQ_ID)
		AND NVP_SEQ_ID = @P_NVP_SEQ_ID
		AND PERMISSIONS_NVP_SEQ_DET_ID = @P_PERMISSIONS_SEQ_ID

	SELECT @P_ErrorCode = @@error
END
