CREATE PROCEDURE [ZFP_GET_ACCTS_NI_GRP]
	@P_SE_SEQ_ID INT,
	@P_GROUP_SEQ_ID INT,
	@P_ErrorCode INT OUTPUT
AS
SELECT
	ACCT
FROM
	ZFC_ACCTS
WHERE
	ACCT NOT IN(
		SELECT
			Accounts.ACCT
		FROM
			ZFC_ACCTS Accounts,
			ZFC_SECURITY_ACCTS_GRPS AcctSecurity,
			ZFC_SECURITY_GRPS_SE Security,
			ZFC_SECURITY_GRPS Groups
		WHERE
			Accounts.ACCT_SEQ_ID = AcctSecurity.ACCT_SEQ_ID
			AND AcctSecurity.GRPS_SE_SEQ_ID = Security.GRPS_SE_SEQ_ID
			AND Security.GROUP_SEQ_ID = Groups.GROUP_SEQ_ID
			AND Accounts.STATUS_SEQ_ID <> 2
			AND Groups.GROUP_SEQ_ID = @P_GROUP_SEQ_ID
			AND Security.SE_SEQ_ID = @P_SE_SEQ_ID
		    )
ORDER BY
	ACCT

SELECT @P_ErrorCode=@@ERROR
