CREATE PROCEDURE [ZFP_GET_GROUP_ROLES] (
	@P_SE_SEQ_ID AS INT,
	@P_GROUP_SEQ_ID AS INT,
	@P_ErrorCode INT OUTPUT
)
AS
	SET NOCOUNT ON
	SELECT [NAME] FROM ZFC_SECURITY_RLS WHERE ROLE_SEQ_ID IN (
		SELECT ROLE_SEQ_ID FROM ZFC_SECURITY_RLS_SE WHERE RLS_SE_SEQ_ID IN (
			SELECT RLS_SE_SEQ_ID FROM ZFC_SECURITY_GRPS_RLS WHERE GRPS_SE_SEQ_ID IN (
				SELECT GRPS_SE_SEQ_ID FROM ZFC_SECURITY_GRPS_SE WHERE SE_SEQ_ID = @P_SE_SEQ_ID AND GROUP_SEQ_ID = @P_GROUP_SEQ_ID)))
	-- Get the Error Code for the statement just executed.
	SELECT @P_ErrorCode=@@ERROR
