CREATE PROCEDURE [ZFP_GET_NVP_GRPS]
	@P_NVP_SEQ_ID int,
	@P_SE_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
AS
-- SELECT one or more existing rows from the table.

SELECT
	ZFC_SECURITY_GRPS.[NAME] AS GROUPS
FROM
	ZFC_SECURITY_NVP_GRPS,
	ZFC_SECURITY_GRPS_SE,
	ZFC_SECURITY_GRPS
WHERE
	ZFC_SECURITY_NVP_GRPS.NVP_SEQ_ID = @P_NVP_SEQ_ID
	AND ZFC_SECURITY_NVP_GRPS.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID
	AND ZFC_SECURITY_GRPS_SE.GROUP_SEQ_ID = ZFC_SECURITY_GRPS.GROUP_SEQ_ID
	AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
ORDER BY
	GROUPS

-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
