CREATE PROCEDURE [ZFP_GET_FUNCTION]
	@P_FUNCTION_SEQ_ID int,
	@P_ErrorCode int OUTPUT
AS
IF @P_FUNCTION_SEQ_ID <> -1
	BEGIN -- SELECT an existing row from the table.
		SELECT
			FUNCTION_SEQ_ID,
			[NAME],
			[DESCRIPTION],
			FUNCTION_TYPE_SEQ_ID,
			SOURCE,
			ENABLE_VIEW_STATE,
			ENABLE_NOTIFICATIONS,
			REDIRECT_ON_TIMEOUT,
			IS_NAV,
			NO_UI,
			NAVIGATION_NVP_SEQ_DET_ID,
			META_KEY_WORDS,
			[ACTION],
			PARENT_FUNCTION_SEQ_ID,
			NOTES,
			ADDED_BY,
			ADDED_DATE,
			UPDATED_BY,
			UPDATED_DATE
		FROM
			ZFC_FUNCTIONS
		WHERE
			FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID
		ORDER BY 
			FUNCTION_SEQ_ID ASC
	END
ELSE
	BEGIN
		SELECT
			FUNCTION_SEQ_ID,
			[NAME],
			[DESCRIPTION],
			FUNCTION_TYPE_SEQ_ID,
			SOURCE,
			ENABLE_VIEW_STATE,
			ENABLE_NOTIFICATIONS,
			REDIRECT_ON_TIMEOUT,
			IS_NAV,
			NO_UI,
			NAVIGATION_NVP_SEQ_DET_ID,
			META_KEY_WORDS,
			[ACTION],
			PARENT_FUNCTION_SEQ_ID,
			NOTES,
			ADDED_BY,
			ADDED_DATE,
			UPDATED_BY,
			UPDATED_DATE
		FROM
			ZFC_FUNCTIONS
		ORDER BY 
			FUNCTION_SEQ_ID ASC
	END

-- END IF
-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
