CREATE PROCEDURE [ZFP_DEL_ACCT_GRP_SECURITY](
	@P_ACCT_SEQ_ID		INT,
	@P_SE_SEQ_ID		INT,
	@P_ADDUPD_BY		INT,
	@P_ErrorCode 		INT OUTPUT
)
 AS
BEGIN
	DELETE FROM 
		ZFC_SECURITY_ACCTS_GRPS 
	WHERE 
		GRPS_SE_SEQ_ID IN(SELECT GRPS_SE_SEQ_ID FROM ZFC_SECURITY_GRPS_SE WHERE SE_SEQ_ID = @P_SE_SEQ_ID)
		AND ACCT_SEQ_ID = @P_ACCT_SEQ_ID
	--PRINT('@@error = ' + CONVERT(VARCHAR,@@error))
	SELECT @P_ErrorCode = @@error
END
