CREATE PROCEDURE [ZFP_GET_ACCT_GRPS]
	@P_ACCOUNT VARCHAR(50),
	@P_SE_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
AS
-- SELECT one or more existing rows from the table.

SELECT
	ZFC_SECURITY_GRPS.[NAME] AS GROUPS
FROM
	ZFC_ACCTS,
	ZFC_SECURITY_ACCTS_GRPS,
	ZFC_SECURITY_GRPS_SE,
	ZFC_SECURITY_GRPS
WHERE
	ZFC_ACCTS.ACCT = @P_ACCOUNT
	AND ZFC_ACCTS.ACCT_SEQ_ID = ZFC_SECURITY_ACCTS_GRPS.ACCT_SEQ_ID
	AND ZFC_SECURITY_ACCTS_GRPS.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID
	AND ZFC_SECURITY_GRPS_SE.GROUP_SEQ_ID = ZFC_SECURITY_GRPS.GROUP_SEQ_ID
	AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
ORDER BY
	GROUPS

-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
