ALTER TABLE [ZGWOptional].[Zip_Codes]
    ADD CONSTRAINT [UK_ZGWOptional_Zip_Codes] UNIQUE NONCLUSTERED ([State] ASC, [Zip_Code] ASC, [City] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

