USE [GWStable]
GO
/****** Object:  StoredProcedure [dbo].[ZFP_GET_FUNCTION_GRPS]    Script Date: 05/25/2012 15:46:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ZFP_GET_FUNCTION_GRPS]
	@P_SE_SEQ_ID INT,
	@P_FUNCTION_SEQ_ID INT,
	@P_PERMISSIONS_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
AS
-- SELECT one or more existing rows from the table.
IF @P_FUNCTION_SEQ_ID > 0
	BEGIN
		SELECT
			ZFC_SECURITY_GRPS.[NAME] AS Groups
		FROM
			ZFC_FUNCTIONS,
			ZFC_SECURITY_FUNCT_GRPS,
			ZFC_SECURITY_GRPS_SE,
			ZFC_SECURITY_GRPS
		WHERE
			ZFC_FUNCTIONS.FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID
			AND ZFC_FUNCTIONS.FUNCTION_SEQ_ID = ZFC_SECURITY_FUNCT_GRPS.FUNCTION_SEQ_ID
			AND ZFC_SECURITY_FUNCT_GRPS.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID
			AND ZFC_SECURITY_FUNCT_GRPS.PERMISSIONS_NVP_SEQ_DET_ID = @P_PERMISSIONS_SEQ_ID
			AND ZFC_SECURITY_GRPS_SE.GROUP_SEQ_ID = ZFC_SECURITY_GRPS.GROUP_SEQ_ID
			AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
		ORDER BY
			Groups
	END
ELSE
	BEGIN
		IF @P_PERMISSIONS_SEQ_ID > 0
			BEGIN
				SELECT
					ZFC_FUNCTIONS.FUNCTION_SEQ_ID
					,ZFC_SECURITY_FUNCT_GRPS.PERMISSIONS_NVP_SEQ_DET_ID AS 'PERMISSIONS_SEQ_ID'
					,ZFC_SECURITY_GRPS.[NAME] AS [Group]
				FROM
					ZFC_FUNCTIONS,
					ZFC_SECURITY_FUNCT_GRPS,
					ZFC_SECURITY_GRPS_SE,
					ZFC_SECURITY_GRPS
				WHERE
					ZFC_FUNCTIONS.FUNCTION_SEQ_ID = ZFC_SECURITY_FUNCT_GRPS.FUNCTION_SEQ_ID
					AND ZFC_SECURITY_FUNCT_GRPS.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID
					AND ZFC_SECURITY_FUNCT_GRPS.PERMISSIONS_NVP_SEQ_DET_ID = @P_PERMISSIONS_SEQ_ID
					AND ZFC_SECURITY_GRPS_SE.GROUP_SEQ_ID = ZFC_SECURITY_GRPS.GROUP_SEQ_ID
					AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
				ORDER BY
					FUNCTION_SEQ_ID
					, PERMISSIONS_SEQ_ID
					,[Group]
			END
		ELSE
			BEGIN
				SELECT
					ZFC_FUNCTIONS.FUNCTION_SEQ_ID
					,ZFC_SECURITY_FUNCT_GRPS.PERMISSIONS_NVP_SEQ_DET_ID AS 'PERMISSIONS_SEQ_ID'
					,ZFC_SECURITY_GRPS.[NAME] AS [Group]
				FROM
					ZFC_FUNCTIONS,
					ZFC_SECURITY_FUNCT_GRPS,
					ZFC_SECURITY_GRPS_SE,
					ZFC_SECURITY_GRPS
				WHERE
					ZFC_FUNCTIONS.FUNCTION_SEQ_ID = ZFC_SECURITY_FUNCT_GRPS.FUNCTION_SEQ_ID
					AND ZFC_SECURITY_FUNCT_GRPS.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID
					AND ZFC_SECURITY_GRPS_SE.GROUP_SEQ_ID = ZFC_SECURITY_GRPS.GROUP_SEQ_ID
					AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
				ORDER BY
					FUNCTION_SEQ_ID
					, PERMISSIONS_SEQ_ID
					,[Group]
			
			END
		--END IF
	END
--END IF
-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
