USE [GWStable]
GO
/****** Object:  StoredProcedure [dbo].[ZFP_GET_FUNCTION_RLS]    Script Date: 05/25/2012 15:40:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ZFP_GET_FUNCTION_RLS]
	@P_SE_SEQ_ID INT,
	@P_FUNCTION_SEQ_ID INT,
	@P_PERMISSIONS_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
AS
-- SELECT one or more existing rows from the table.
IF @P_FUNCTION_SEQ_ID > 0
	BEGIN
		SELECT
			ZFC_SECURITY_RLS.[NAME] AS ROLES
		FROM
			ZFC_FUNCTIONS,
			ZFC_SECURITY_FUNCT_RLS,
			ZFC_SECURITY_RLS_SE,
			ZFC_SECURITY_RLS
		WHERE
			ZFC_FUNCTIONS.FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID
			AND ZFC_FUNCTIONS.FUNCTION_SEQ_ID = ZFC_SECURITY_FUNCT_RLS.FUNCTION_SEQ_ID
			AND ZFC_SECURITY_FUNCT_RLS.RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
			AND ZFC_SECURITY_FUNCT_RLS.PERMISSIONS_NVP_SEQ_DET_ID = @P_PERMISSIONS_SEQ_ID
			AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
			AND ZFC_SECURITY_RLS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
		ORDER BY
			ROLES
	END
ELSE
	BEGIN
		IF @P_PERMISSIONS_SEQ_ID > 0
			BEGIN
				SELECT
					ZFC_FUNCTIONS.FUNCTION_SEQ_ID
					,ZFC_SECURITY_FUNCT_RLS.PERMISSIONS_NVP_SEQ_DET_ID AS 'PERMISSIONS_SEQ_ID'
					,ZFC_SECURITY_RLS.[NAME] AS [ROLE]
				FROM
					ZFC_FUNCTIONS,
					ZFC_SECURITY_FUNCT_RLS,
					ZFC_SECURITY_RLS_SE,
					ZFC_SECURITY_RLS
				WHERE
					ZFC_FUNCTIONS.FUNCTION_SEQ_ID = ZFC_SECURITY_FUNCT_RLS.FUNCTION_SEQ_ID
					AND ZFC_SECURITY_FUNCT_RLS.RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
					AND ZFC_SECURITY_FUNCT_RLS.PERMISSIONS_NVP_SEQ_DET_ID = @P_PERMISSIONS_SEQ_ID
					AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
					AND ZFC_SECURITY_RLS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
				ORDER BY
					FUNCTION_SEQ_ID
					, PERMISSIONS_SEQ_ID
					, [ROLE]
			END
		ELSE
			BEGIN
				SELECT
					ZFC_FUNCTIONS.FUNCTION_SEQ_ID
					,ZFC_SECURITY_FUNCT_RLS.PERMISSIONS_NVP_SEQ_DET_ID AS 'PERMISSIONS_SEQ_ID'
					,ZFC_SECURITY_RLS.[NAME] AS [ROLE]
				FROM
					ZFC_FUNCTIONS,
					ZFC_SECURITY_FUNCT_RLS,
					ZFC_SECURITY_RLS_SE,
					ZFC_SECURITY_RLS
				WHERE
					ZFC_FUNCTIONS.FUNCTION_SEQ_ID = ZFC_SECURITY_FUNCT_RLS.FUNCTION_SEQ_ID
					AND ZFC_SECURITY_FUNCT_RLS.RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
					AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
					AND ZFC_SECURITY_RLS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
				ORDER BY
					FUNCTION_SEQ_ID
			END
		--END IF			
	END
--END IF
-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
