ALTER TABLE [ZGWOptional].[Directories]
    ADD CONSTRAINT [PK_Directories] PRIMARY KEY CLUSTERED ([Function_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

