CREATE UNIQUE NONCLUSTERED INDEX [UX_ZGWSecurity_Roles_Security_Entities]
    ON [ZGWSecurity].[Roles_Security_Entities]([Role_SeqID] ASC, [Security_Entity_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

