'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddEditWebConfig

    '''<summary>
    '''frmAddEditWebConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmAddEditWebConfig As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dropAppend_To_File control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropAppend_To_File As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropAlways_Left_Nav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropAlways_Left_Nav As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtApp_Displayed_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApp_Displayed_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSecurity_Entity_Translation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecurity_Entity_Translation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBase_Page control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBase_Page As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropCentralManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropCentralManagement As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtConversion_Pattern control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConversion_Pattern As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDefault_Action control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefault_Action As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDefault_Authenticated_Action control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefault_Authenticated_Action As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtExpected_Up_By control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpected_Up_By As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropEncryption_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropEncryption_Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropEnforce_Action control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropEnforce_Action As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropEnvironment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropEnvironment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropDB_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDB_Status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropServer_Side_View_State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropServer_Side_View_State As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtServer_Side_View_State_Pages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServer_Side_View_State_Pages As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropUnder_Construction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropUnder_Construction As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropEnvironments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropEnvironments As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDelete As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNewEnvironment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewEnvironment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEnvironments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvironments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApp_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApp_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropAuthentication_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropAuthentication_Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropAuto_Create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropAuto_Create As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAuto_Create_ClientChoicesAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuto_Create_ClientChoicesAccount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAuto_Create_SecurityEntity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuto_Create_SecurityEntity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAuto_Create_Roles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuto_Create_Roles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropDAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDAL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAssembly_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssembly_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtName_Space control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName_Space As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtConnectionstring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConnectionstring As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hyperConnectionString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperConnectionString As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''txtDefault_Security_Entity_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefault_Security_Entity_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropEnable_Cache control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropEnable_Cache As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropEnable_Encryption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropEnable_Encryption As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropEnable_Pooling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropEnable_Pooling As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropForce_HTTPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropForce_HTTPS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLDAP_Domain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLDAP_Domain As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLDAP_Server control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLDAP_Server As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLog_Path control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLog_Path As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLogRetention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogRetention As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RangeValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txtRegisteringRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegisteringRoles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRegistration_Post_Action control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegistration_Post_Action As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropLog_Priority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropLog_Priority As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropSkin_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropSkin_Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSMTP_Server control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMTP_Server As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSMTP_Account control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMTP_Account As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSMTP_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMTP_Password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSMTP_From control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMTP_From As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropSynchronize_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropSynchronize_Password As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFailedAttempts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFailedAttempts As Global.System.Web.UI.WebControls.TextBox
End Class
