ALTER TABLE [ZGWOptional].[Calendars]
    ADD CONSTRAINT [PK_ZGWOptional_Calendars] PRIMARY KEY CLUSTERED ([Security_Entity_SeqID] ASC, [Added_By] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

