ALTER TABLE [ZGWOptional].[Zip_Codes]
    ADD CONSTRAINT [PK_Zip_Codes] PRIMARY KEY CLUSTERED ([State] ASC, [Zip_Code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

