ALTER TABLE [ZGWCoreWeb].[Account_Choices]
    ADD CONSTRAINT [PK_Account_Choices] PRIMARY KEY CLUSTERED ([Account] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

