ALTER TABLE [dbo].[ZFC_SECURITY_RLS_SE]
    ADD CONSTRAINT [FK_ZFC_SECURITY_RLS_SE_ZFC_SECURITY_RLS] FOREIGN KEY ([ROLE_SEQ_ID]) REFERENCES [dbo].[ZFC_SECURITY_RLS] ([ROLE_SEQ_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

