ALTER TABLE [dbo].[ZFC_SECURITY_FUNCT_RLS]
    ADD CONSTRAINT [FK_ZFC_FUNCT_RLS_SECURITY_ZFC_FUNCTIONS] FOREIGN KEY ([FUNCTION_SEQ_ID]) REFERENCES [dbo].[ZFC_FUNCTIONS] ([FUNCTION_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

