ALTER TABLE [dbo].[ZFC_PERMISSIONS]
    ADD CONSTRAINT [FK_ZFC_PERMISSIONS_ZFC_SYSTEM_STATUS] FOREIGN KEY ([STATUS_SEQ_ID]) REFERENCES [dbo].[ZFC_SYSTEM_STATUS] ([STATUS_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

