ALTER TABLE [dbo].[ZOP_CALENDAR]
    ADD CONSTRAINT [FK_ZOP_CALENDAR_ZFC_SECURITY_ENTITIES] FOREIGN KEY ([SE_SEQ_ID]) REFERENCES [dbo].[ZFC_SECURITY_ENTITIES] ([SE_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

