ALTER TABLE [dbo].[ZFC_SECURITY_GRPS_RLS]
    ADD CONSTRAINT [FK_ZFC_SECURITY_GRPS_RLS_ZFC_SECURITY_RLS_SE] FOREIGN KEY ([RLS_SE_SEQ_ID]) REFERENCES [dbo].[ZFC_SECURITY_RLS_SE] ([RLS_SE_SEQ_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

