ALTER TABLE [dbo].[ZFC_NAVIGATION_TYPES]
    ADD CONSTRAINT [FK_ZFC_NAVIGATION_TYPES_ZFC_SYSTEM_STATUS] FOREIGN KEY ([STATUS_SEQ_ID]) REFERENCES [dbo].[ZFC_SYSTEM_STATUS] ([STATUS_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

