ALTER TABLE [dbo].[ZOP_STATES]
    ADD CONSTRAINT [FK_ZOP_STATES_ZFC_SYSTEM_STATUS] FOREIGN KEY ([STATUS_SEQ_ID]) REFERENCES [dbo].[ZFC_SYSTEM_STATUS] ([STATUS_SEQ_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

