ALTER TABLE [dbo].[ZFC_SECURITY_GRPS_SE]
    ADD CONSTRAINT [FK_ZFC_SECURITY_GRPS_SE_ZFC_SECURITY_ENTITIES] FOREIGN KEY ([SE_SEQ_ID]) REFERENCES [dbo].[ZFC_SECURITY_ENTITIES] ([SE_SEQ_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

