ALTER TABLE [dbo].[ZFC_NAVIGATION_TYPES]
    ADD CONSTRAINT [FK_ZFC_NAVIGATION_TYPES_ZFC_NVP] FOREIGN KEY ([NVP_SEQ_ID]) REFERENCES [dbo].[ZFC_NVP] ([NVP_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

