ALTER TABLE [dbo].[ZFC_FUNCTIONS]
    ADD CONSTRAINT [FK_ZFC_FUNCTIONS_ZFC_FUNCTION_TYPES] FOREIGN KEY ([FUNCTION_TYPE_SEQ_ID]) REFERENCES [dbo].[ZFC_FUNCTION_TYPES] ([FUNCTION_TYPE_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

