ALTER TABLE [dbo].[ZFC_FUNCTIONS]
    ADD CONSTRAINT [FK_ZFC_FUNCTIONS_ZFC_NAVIGATION_TYPES] FOREIGN KEY ([NAVIGATION_NVP_SEQ_DET_ID]) REFERENCES [dbo].[ZFC_NAVIGATION_TYPES] ([NVP_SEQ_DET_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

