ALTER TABLE [dbo].[ZFC_SECURITY_NVP_GRPS]
    ADD CONSTRAINT [FK_ZFC_NVP_GRPS_SEC_ZFC_NVP] FOREIGN KEY ([NVP_SEQ_ID]) REFERENCES [dbo].[ZFC_NVP] ([NVP_SEQ_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

