ALTER TABLE [dbo].[ZFC_ACCTS]
    ADD CONSTRAINT [FK_ZFC_ACCTS_ZFC_SYSTEM_STATUS] FOREIGN KEY ([STATUS_SEQ_ID]) REFERENCES [dbo].[ZFC_SYSTEM_STATUS] ([STATUS_SEQ_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

