ALTER TABLE [dbo].[ZFC_SECURITY_NVP_RLS]
    ADD CONSTRAINT [FK_ZFC_SECURITY_NVP_RLS_ZFC_PERMISSIONS] FOREIGN KEY ([PERMISSIONS_NVP_SEQ_DET_ID]) REFERENCES [dbo].[ZFC_PERMISSIONS] ([NVP_SEQ_DET_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

