ALTER TABLE [dbo].[ZFC_NVP]
    ADD CONSTRAINT [PK_ZFC_NVP] PRIMARY KEY CLUSTERED ([NVP_SEQ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

