ALTER TABLE [dbo].[ZFC_SYSTEM_STATUS]
    ADD CONSTRAINT [PK_ZFC_SYSTEM_STATUS] PRIMARY KEY CLUSTERED ([STATUS_SEQ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

