ALTER TABLE [dbo].[ZFO_WORK_FLOWS]
    ADD CONSTRAINT [UK_ZFO_WORK_FLOWS] UNIQUE NONCLUSTERED ([NVP_DET_VALUE] ASC, [NVP_DET_TEXT] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

