ALTER TABLE [dbo].[ZFC_SECURITY_FUNCT_RLS]
    ADD CONSTRAINT [UK_ZFC_FUNCT_PER_RLS] UNIQUE NONCLUSTERED ([PERMISSIONS_NVP_SEQ_DET_ID] ASC, [RLS_SE_SEQ_ID] ASC, [FUNCTION_SEQ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

