ALTER TABLE [dbo].[ZFC_SECURITY_RLS]
    ADD CONSTRAINT [UK_ZFC_RLS] UNIQUE NONCLUSTERED ([NAME] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

