CREATE TABLE [dbo].[ZFC_SECURITY_GRPS] (
    [GROUP_SEQ_ID] INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NAME]         VARCHAR (128) NOT NULL,
    [DESCRIPTION]  VARCHAR (512) NOT NULL,
    [ADDED_BY]     INT           NOT NULL,
    [ADDED_DATE]   DATETIME      DEFAULT (getdate()) NOT NULL,
    [UPDATED_BY]   INT           NOT NULL,
    [UPDATED_DATE] DATETIME      NOT NULL
);

