CREATE TABLE [dbo].[ZFC_SECURITY_GRPS_SE] (
    [GRPS_SE_SEQ_ID] INT      IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SE_SEQ_ID]      INT      NOT NULL,
    [GROUP_SEQ_ID]   INT      NOT NULL,
    [ADDED_BY]       INT      NOT NULL,
    [ADDED_DATE]     DATETIME DEFAULT (getdate()) NOT NULL
);

