CREATE TABLE [dbo].[ZFC_SECURITY_RLS_SE] (
    [RLS_SE_SEQ_ID] INT      IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SE_SEQ_ID]     INT      NOT NULL,
    [ROLE_SEQ_ID]   INT      NOT NULL,
    [ADDED_BY]      INT      NOT NULL,
    [ADDED_DATE]    DATETIME NOT NULL
);

