ALTER TABLE [ZGWSecurity].[Function_Types]
    ADD CONSTRAINT [UK_ZGWCoreWeb_Function_Types] UNIQUE NONCLUSTERED ([Name] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

