ALTER TABLE [ZGWSystem].[Statuses]
    ADD CONSTRAINT [PK_ZGWSystem_Statuses] PRIMARY KEY CLUSTERED ([Status_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

