ALTER TABLE [ZGWOptional].[States]
    ADD CONSTRAINT [PK_ZGWOptional_States] PRIMARY KEY CLUSTERED ([State] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

