ALTER TABLE [ZGWSecurity].[Roles_Security_Entities]
    ADD CONSTRAINT [PK_Roles_Security_Entities] PRIMARY KEY CLUSTERED ([Roles_Security_Entities_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

