'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''GUIDHelper class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class GUIDHelper

	'''<summary>
	'''litOutput control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litOutput As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''btnGUID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnGUID As Global.System.Web.UI.WebControls.Button
End Class
