'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''AccessDenied class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class AccessDenied

	'''<summary>
	'''insufficientRights control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents insufficientRights As Global.System.Web.UI.WebControls.PlaceHolder

	'''<summary>
	'''requesedAction control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents requesedAction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''mustLogon control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents mustLogon As Global.System.Web.UI.WebControls.PlaceHolder

	'''<summary>
	'''requesedAction1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents requesedAction1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
