ALTER TABLE [ZGWSecurity].[Functions]
    ADD CONSTRAINT [UK_ZGWSecurity_Functions] UNIQUE NONCLUSTERED ([Action] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

