//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GrowthWare.Framework.DataAccessLayer
{
	using GrowthWare.Framework.ModelObjects;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IDAccount 
	{
		object Profile { get;set; }

		MAccountProfile GetAccount { get;set; }

		int SecurityEntitySeqID { get;set; }

		object GetAccounts { get;set; }

		void SaveGroups();

		void GetRoles();

		void GetGroups();

		void GetSecurity();

		void Delete();

		void Save();

		void SaveRoles();

	}
}

