'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''AccountsGeneral class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class AccountsGeneral

	'''<summary>
	'''txtAccount_seq_id control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAccount_seq_id As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblError control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''litAccount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litAccount As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''txtAccount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAccount As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''litAccountWarning control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litAccountWarning As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''RequiredFieldValidator1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''dropStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dropStatus As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''litFailedAttempts control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litFailedAttempts As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''txtFailedAttempts control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFailedAttempts As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Requiredfieldvalidator5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Requiredfieldvalidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''txtLastName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Requiredfieldvalidator6 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Requiredfieldvalidator6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''txtMiddleName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMiddleName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtPreferedName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPreferedName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Requiredfieldvalidator4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Requiredfieldvalidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''txtEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Requiredfieldvalidator2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Requiredfieldvalidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''Regularexpressionvalidator1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Regularexpressionvalidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''dropTimezone control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dropTimezone As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtLocation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''chkEnableNotifications control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkEnableNotifications As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
