'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''EditProfile class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class EditProfile

	'''<summary>
	'''litAccountName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litAccountName As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''Tabstrip1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Tabstrip1 As Global.ApplicationBase.Common.CustomWebControls.TabStrip

	'''<summary>
	'''Tab1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Tab1 As Global.ApplicationBase.Common.CustomWebControls.Tab

	'''<summary>
	'''RolesTab control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RolesTab As Global.ApplicationBase.Common.CustomWebControls.Tab

	'''<summary>
	'''GroupsTab control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents GroupsTab As Global.ApplicationBase.Common.CustomWebControls.Tab

	'''<summary>
	'''bottomTabStrip control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents bottomTabStrip As Global.System.Web.UI.HtmlControls.HtmlTableCell

	'''<summary>
	'''pnlGeneral control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlGeneral As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''AccountsGeneral control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AccountsGeneral As Global.ApplicationBase.AccountsGeneral

	'''<summary>
	'''pnlRoles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlRoles As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''AccountRoles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AccountRoles As Global.ApplicationBase.AccountRoles

	'''<summary>
	'''pnlGroups control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlGroups As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''AccountGroups control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AccountGroups As Global.ApplicationBase.AccountGroups

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
