CREATE PROCEDURE [ZFP_GET_NVP_RLS]
	@P_NVP_SEQ_ID int,
	@P_SE_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
AS
-- SELECT one or more existing rows from the table.

SELECT
	ZFC_SECURITY_RLS.[NAME] AS ROLES
FROM
	ZFC_SECURITY_NVP_RLS,
	ZFC_SECURITY_RLS_SE,
	ZFC_SECURITY_RLS
WHERE
	ZFC_SECURITY_NVP_RLS.NVP_SEQ_ID = @P_NVP_SEQ_ID
	AND ZFC_SECURITY_NVP_RLS.RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
ORDER BY
	ROLES

-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
