



CREATE PROCEDURE [ZFP_SET_NOTIFICATIONS] 
(
  @P_SE_SEQ_ID int,
  @P_FUNCTION_SEQ_ID int,
  @P_ACCOUNT Varchar(128),
  @P_STATUS int
)
AS
-- GET Account ID
DECLARE @V_ACCT_SEQ_ID int
SET @V_ACCT_SEQ_ID = (SELECT ACCT_SEQ_ID FROM ZFC_ACCTS WHERE ACCT = @P_ACCOUNT)

IF @P_STATUS = 1
	BEGIN
	  IF NOT EXISTS
		(
			SELECT 
				ADDED_BY 
			FROM 
				ZFC_NOTIFICATIONS 
			WHERE 
				SE_SEQ_ID = @P_SE_SEQ_ID
				AND FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID
				AND ADDED_BY = @V_ACCT_SEQ_ID
		)
		  INSERT ZFC_NOTIFICATIONS
		  (
    		SE_SEQ_ID,
			FUNCTION_SEQ_ID,
			ADDED_BY
		  )
		  VALUES
		  (
			@P_SE_SEQ_ID,
			@P_FUNCTION_SEQ_ID,
			@V_ACCT_SEQ_ID
		  )
	END
ELSE
	DELETE 
		ZFC_NOTIFICATIONS
	WHERE 
		SE_SEQ_ID = @P_SE_SEQ_ID
		AND FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID
		AND ADDED_BY = @V_ACCT_SEQ_ID
