CREATE PROCEDURE [ZFP_SET_SECURITY_ENTITIES]
	@P_SE_SEQ_ID int,
	@P_NAME VARCHAR(256),
	@P_DESCRIPTION VARCHAR(512),
	@P_URL VARCHAR(128),
	@P_STATUS_SEQ_ID int,
	@P_DAL VARCHAR(50),
	@P_DAL_NAME VARCHAR(50),
	@P_DAL_NAME_SPACE VARCHAR(256),
	@P_DAL_STRING VARCHAR(512),
	@P_SKIN char(25),
	@P_STYLE VARCHAR(25),
	@P_ENCRYPTION_TYPE INT,
	@P_PARENT_SE_SEQ_ID int,
	@P_ADDED_UPDATED_BY INT,
	@P_ADDED_UPDATED_DATE DATETIME,
	@P_PRIMARY_KEY int OUTPUT,
	@P_ErrorCode int OUTPUT
AS
SET NOCOUNT ON
	IF @P_PARENT_SE_SEQ_ID = @P_SE_SEQ_ID or @P_PARENT_SE_SEQ_ID = -1 SET @P_PARENT_SE_SEQ_ID = NULL
	IF @P_SE_SEQ_ID > -1
		BEGIN
			UPDATE ZFC_SECURITY_ENTITIES
			SET 
				NAME = @P_NAME,
				DESCRIPTION = @P_DESCRIPTION,
				URL = @P_URL,
				STATUS_SEQ_ID = @P_STATUS_SEQ_ID,
				DAL = @P_DAL,
				DAL_NAME = @P_DAL_NAME,
				DAL_NAME_SPACE = @P_DAL_NAME_SPACE,
				DAL_STRING = @P_DAL_STRING,
				SKIN = @P_SKIN,
				STYLE = @P_STYLE,
				ENCRYPTION_TYPE = @P_ENCRYPTION_TYPE,
				PARENT_SE_SEQ_ID = @P_PARENT_SE_SEQ_ID,
				UPDATED_BY = @P_ADDED_UPDATED_BY,
				UPDATED_DATE = @P_ADDED_UPDATED_DATE
			WHERE
				SE_SEQ_ID = @P_SE_SEQ_ID

			SELECT @P_PRIMARY_KEY = @P_SE_SEQ_ID
		END
	ELSE
		BEGIN
			-- INSERT a new row in the table.
			INSERT ZFC_SECURITY_ENTITIES
			(
				[NAME],
				[DESCRIPTION],
				[URL],
				STATUS_SEQ_ID,
				DAL,
				DAL_NAME,
				DAL_NAME_SPACE,
				DAL_STRING,
				SKIN,
				STYLE,
				ENCRYPTION_TYPE,
				PARENT_SE_SEQ_ID,
				ADDED_BY,
				ADDED_DATE,
				UPDATED_BY,
				UPDATED_DATE
			)
			VALUES
			(
				@P_NAME,
				@P_DESCRIPTION,
				@P_URL,
				@P_STATUS_SEQ_ID,
				@P_DAL,
				@P_DAL_NAME,
				@P_DAL_NAME_SPACE,
				@P_DAL_STRING,
				@P_SKIN,
				@P_STYLE,
				@P_ENCRYPTION_TYPE,
				@P_PARENT_SE_SEQ_ID,
				@P_ADDED_UPDATED_BY,
				@P_ADDED_UPDATED_DATE,
				@P_ADDED_UPDATED_BY,
				@P_ADDED_UPDATED_DATE
			)	
			-- Get the IDENTITY value for the row just inserted.
			SELECT @P_PRIMARY_KEY=SCOPE_IDENTITY()
		END
-- End if
-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
