CREATE PROCEDURE [ZFP_GET_ACCT_RLS]
	@P_ACCOUNT VARCHAR(50),
	@P_SE_SEQ_ID INT,
	@P_ErrorCode int OUTPUT
AS
-- SELECT one or more existing rows from the table.

SELECT
	ZFC_SECURITY_RLS.[NAME] AS ROLES
FROM
	ZFC_ACCTS,
	ZFC_SECURITY_ACCTS_RLS,
	ZFC_SECURITY_RLS_SE,
	ZFC_SECURITY_RLS
WHERE
	ZFC_ACCTS.ACCT = @P_ACCOUNT
	AND ZFC_ACCTS.ACCT_SEQ_ID = ZFC_SECURITY_ACCTS_RLS.ACCT_SEQ_ID
	AND ZFC_SECURITY_ACCTS_RLS.RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.SE_SEQ_ID = @P_SE_SEQ_ID
ORDER BY
	ROLES

-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
