CREATE PROCEDURE [ZFP_GET_MENU_DATA](
	@P_SE_SEQ_ID INT,
	@P_NAV_TYPE_ID INT,
	@P_ACCT VARCHAR(50),
	@P_ErrorCode int OUTPUT
) AS
DECLARE @V_PERMISSION_ID INT
SET @V_PERMISSION_ID = dbo.ZFF_GET_VIEW_PERMISSION_ID()
DECLARE @V_AvalibleItems TABLE ([ID] INT, TITLE VARCHAR(30), [DESCRIPTION] VARCHAR(256), URL VARCHAR(256), PARENT INT, SORT_ORDER INT, ROLE VARCHAR(50),FUNCTION_TYPE_SEQ_ID INT)
INSERT INTO @V_AvalibleItems
SELECT -- Menu items via roles
	[FUNCTIONS].FUNCTION_SEQ_ID AS [ID],
	[FUNCTIONS].[NAME] AS TITLE,
	[FUNCTIONS].[DESCRIPTION],
	[FUNCTIONS].[ACTION] AS URL,
	[FUNCTIONS].PARENT_FUNCTION_SEQ_ID AS PARENT,
	[FUNCTIONS].SORT_ORDER AS SORT_ORDER,
	ROLES.[NAME] AS ROLE,
	[FUNCTIONS].FUNCTION_TYPE_SEQ_ID
FROM
	ZFC_SECURITY_RLS_SE SE_ROLES,
	ZFC_SECURITY_RLS ROLES,
	ZFC_SECURITY_FUNCT_RLS SECURITY,
	ZFC_FUNCTIONS [FUNCTIONS],
	ZFC_PERMISSIONS [PERMISSIONS]
WHERE
	SE_ROLES.ROLE_SEQ_ID = ROLES.ROLE_SEQ_ID
	AND SECURITY.RLS_SE_SEQ_ID = SE_ROLES.RLS_SE_SEQ_ID
	AND SECURITY.FUNCTION_SEQ_ID = [FUNCTIONS].FUNCTION_SEQ_ID
	AND [PERMISSIONS].NVP_SEQ_DET_ID = SECURITY.PERMISSIONS_NVP_SEQ_DET_ID
	AND [PERMISSIONS].NVP_SEQ_DET_ID = @V_PERMISSION_ID
	AND [FUNCTIONS].NAVIGATION_NVP_SEQ_DET_ID = @P_NAV_TYPE_ID
	AND [FUNCTIONS].IS_NAV = 1
	AND SE_ROLES.SE_SEQ_ID IN (SELECT SE_SEQ_ID FROM dbo.ZFF_GET_SE_PARENTS(1,@P_SE_SEQ_ID))
UNION ALL
SELECT -- Menu items via groups
	[FUNCTIONS].FUNCTION_SEQ_ID AS [ID],
	[FUNCTIONS].[NAME] AS TITLE,
	[FUNCTIONS].[DESCRIPTION],
	[FUNCTIONS].[ACTION] AS URL,
	[FUNCTIONS].PARENT_FUNCTION_SEQ_ID AS PARENT,
	[FUNCTIONS].SORT_ORDER AS SORT_ORDER,
	ROLES.[NAME] AS ROLE,
	[FUNCTIONS].FUNCTION_TYPE_SEQ_ID
FROM
	ZFC_SECURITY_FUNCT_GRPS,
	ZFC_SECURITY_GRPS_SE,
	ZFC_SECURITY_GRPS_RLS,
	ZFC_SECURITY_RLS_SE,
	ZFC_SECURITY_RLS ROLES,
	ZFC_FUNCTIONS [FUNCTIONS],
	ZFC_PERMISSIONS [PERMISSIONS]
WHERE
	ZFC_SECURITY_FUNCT_GRPS.FUNCTION_SEQ_ID = [FUNCTIONS].FUNCTION_SEQ_ID
	AND ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID = ZFC_SECURITY_FUNCT_GRPS.GRPS_SE_SEQ_ID
	AND ZFC_SECURITY_GRPS_RLS.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID = ZFC_SECURITY_GRPS_RLS.RLS_SE_SEQ_ID
	AND ROLES.ROLE_SEQ_ID = ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID
	AND [PERMISSIONS].NVP_SEQ_DET_ID = ZFC_SECURITY_FUNCT_GRPS.PERMISSIONS_NVP_SEQ_DET_ID
	AND [PERMISSIONS].NVP_SEQ_DET_ID = @V_PERMISSION_ID
	AND [FUNCTIONS].NAVIGATION_NVP_SEQ_DET_ID = @P_NAV_TYPE_ID
	AND [FUNCTIONS].IS_NAV = 1
	AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID IN (SELECT SE_SEQ_ID FROM dbo.ZFF_GET_SE_PARENTS(1,@P_SE_SEQ_ID))

--SELECT * FROM @V_AvalibleMenuItems -- DEBUG

DECLARE @V_AccountRoles TABLE (Roles VARCHAR(30)) -- Roles belonging to the account
INSERT INTO @V_AccountRoles
SELECT -- Roles via roles
	ZFC_SECURITY_RLS.[NAME] AS Roles
FROM
	ZFC_ACCTS,
	ZFC_SECURITY_ACCTS_RLS,
	ZFC_SECURITY_RLS_SE,
	ZFC_SECURITY_RLS
WHERE
	ZFC_ACCTS.ACCT = @P_ACCT
	AND ZFC_SECURITY_ACCTS_RLS.ACCT_SEQ_ID = ZFC_ACCTS.ACCT_SEQ_ID
	AND ZFC_SECURITY_ACCTS_RLS.RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.SE_SEQ_ID IN (SELECT SE_SEQ_ID FROM dbo.ZFF_GET_SE_PARENTS(1,@P_SE_SEQ_ID))
	AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
UNION
SELECT -- Roles via groups
	ZFC_SECURITY_RLS.[NAME] AS Roles
FROM
	ZFC_ACCTS,
	ZFC_SECURITY_ACCTS_GRPS,
	ZFC_SECURITY_GRPS_SE,
	ZFC_SECURITY_GRPS_RLS,
	ZFC_SECURITY_RLS_SE,
	ZFC_SECURITY_RLS
WHERE
	ZFC_ACCTS.ACCT = @P_ACCT
	AND ZFC_SECURITY_ACCTS_GRPS.ACCT_SEQ_ID = ZFC_ACCTS.ACCT_SEQ_ID
	AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID IN (SELECT SE_SEQ_ID FROM dbo.ZFF_GET_SE_PARENTS(1,@P_SE_SEQ_ID))
	AND ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_RLS.GRPS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID = ZFC_SECURITY_GRPS_RLS.RLS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID

--SELECT * FROM @V_AccountRoles -- DEBUG
DECLARE @V_AllMenuItems TABLE ([ID] INT, TITLE VARCHAR(30), [DESCRIPTION] VARCHAR(256), URL VARCHAR(256), PARENT INT, SORT_ORDER INT, ROLE VARCHAR(50),FUNCTION_TYPE_SEQ_ID INT)
INSERT INTO @V_AllMenuItems
SELECT -- Last but not least get the menu items when there are matching account roles.
	[ID],
	TITLE,
	[DESCRIPTION],
	URL,
	PARENT,
	SORT_ORDER,
	ROLE,
	FUNCTION_TYPE_SEQ_ID
FROM 
	@V_AvalibleItems
WHERE
	ROLE IN (SELECT DISTINCT * FROM @V_AccountRoles)

DECLARE @V_DistinctItems TABLE ([ID] INT, TITLE VARCHAR(30), [DESCRIPTION] VARCHAR(256), URL VARCHAR(256), PARENT INT, SORT_ORDER INT, FUNCTION_TYPE_SEQ_ID INT)
INSERT INTO @V_DistinctItems
SELECT DISTINCT
	[ID],
	TITLE,
	[DESCRIPTION],
	URL,
	PARENT,
	SORT_ORDER,
	FUNCTION_TYPE_SEQ_ID
FROM
	@V_AllMenuItems

SELECT
	ID as MenuID,
	TITLE,
	[DESCRIPTION],
	URL,                                                                                                                                                                                                                                                              
	PARENT as ParentID,
	SORT_ORDER,
	FUNCTION_TYPE_SEQ_ID
FROM
	@V_DistinctItems
ORDER BY
	SORT_ORDER

SELECT @P_ErrorCode = @@Error
