CREATE PROCEDURE [ZFP_DEL_FUNCTION_GRP_SECURITY](
	@P_FUNCTION_SEQ_ID	INT,
	@P_SE_SEQ_ID		INT,
	@P_PERMISSIONS_SEQ_ID	INT,
	@P_ADDUPD_BY		INT,
	@P_ErrorCode 		INT OUTPUT
)
 AS
BEGIN
	DELETE FROM 
		ZFC_SECURITY_FUNCT_GRPS 
	WHERE 
		GRPS_SE_SEQ_ID IN(SELECT GRPS_SE_SEQ_ID FROM ZFC_SECURITY_GRPS_SE WHERE SE_SEQ_ID = @P_SE_SEQ_ID)
		AND FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID

	SELECT @P_ErrorCode = @@error
END
