CREATE PROCEDURE [ZFP_GET_NOTIFICATIONS] 
(
	@P_SE_SEQ_ID int,
	@P_FUNCTION_SEQ_ID int
)
AS
-- GET ACCT_SEQ_ID
DECLARE @V_ENABLE_NOTIFICATIONS Int
SET @V_ENABLE_NOTIFICATIONS = 1 -- True

SELECT
	EMAIL
FROM
	ZFC_ACCTS,
	ZFC_NOTIFICATIONS
WHERE
	ZFC_ACCTS.ENABLE_NOTIFICATIONS = @V_ENABLE_NOTIFICATIONS
	AND ZFC_ACCTS.ACCT_SEQ_ID = ZFC_NOTIFICATIONS.ADDED_BY
	AND ZFC_NOTIFICATIONS.FUNCTION_SEQ_ID = @P_FUNCTION_SEQ_ID
	AND ZFC_NOTIFICATIONS.SE_SEQ_ID = @P_SE_SEQ_ID
