CREATE PROCEDURE [ZFP_SET_NVP_GRPS](
	@P_NVP_SEQ_ID INT,
	@P_SE_SEQ_ID INT,
	@P_GROUPS VARCHAR(1000),
	@P_PERMISSIONS_SEQ_ID INT,
	@P_ADDUPD_BY INT,
	@P_ErrorCode int OUTPUT
)
 AS
BEGIN TRAN
	-- NEED TO DELETE EXISTING GROUP ASSOCITAED WITH THE NVP BEFORE 
	-- INSERTING NEW ONES.
	EXEC ZFP_DEL_NVP_GRP_SECURITY @P_NVP_SEQ_ID,@P_SE_SEQ_ID,@P_PERMISSIONS_SEQ_ID,@P_ADDUPD_BY,@P_ErrorCode
	DECLARE @V_GROUP_SEQ_ID 		AS 	INT
	DECLARE @V_SE_GRPS_SECURITY_ID 	AS 	INT
	DECLARE @V_GROUP_NAME		AS	VARCHAR(50)
	DECLARE @V_Pos 			AS	INT
	SET @P_GROUPS = LTRIM(RTRIM(@P_GROUPS))+ ','
	SET @V_Pos = CHARINDEX(',', @P_GROUPS, 1)
	IF REPLACE(@P_GROUPS, ',', '') <> ''
		WHILE @V_Pos > 0
		BEGIN
			SET @V_GROUP_NAME = LTRIM(RTRIM(LEFT(@P_GROUPS, @V_Pos - 1)))
			IF @V_GROUP_NAME <> ''
			BEGIN
				--select the GROUP seq id first
				SELECT @V_GROUP_SEQ_ID = ZFC_SECURITY_GRPS.GROUP_SEQ_ID 
				FROM ZFC_SECURITY_GRPS 
				WHERE [NAME]=@V_GROUP_NAME

 				SELECT
					@V_SE_GRPS_SECURITY_ID=GRPS_SE_SEQ_ID
				FROM
					ZFC_SECURITY_GRPS_SE
				WHERE
					GROUP_SEQ_ID = @V_GROUP_SEQ_ID AND
					SE_SEQ_ID = @P_SE_SEQ_ID
					--PRINT('@V_SE_GRPS_SECURITY_ID = ' + CONVERT(VARCHAR,@V_SE_GRPS_SECURITY_ID))
				IF NOT EXISTS(
						SELECT 
							GRPS_SE_SEQ_ID 
						FROM 
							ZFC_SECURITY_NVP_GRPS 
						WHERE 
						NVP_SEQ_ID = @P_NVP_SEQ_ID 
						AND PERMISSIONS_NVP_SEQ_DET_ID = @P_PERMISSIONS_SEQ_ID
						AND GRPS_SE_SEQ_ID = @V_SE_GRPS_SECURITY_ID
				)
				BEGIN
					--PRINT('INSERT RECORD')
					INSERT ZFC_SECURITY_NVP_GRPS (
						NVP_SEQ_ID,
						GRPS_SE_SEQ_ID,
						PERMISSIONS_NVP_SEQ_DET_ID,
						ADDED_BY
					)
					VALUES (
						@P_NVP_SEQ_ID,
						@V_SE_GRPS_SECURITY_ID,
						@P_PERMISSIONS_SEQ_ID,
						@P_ADDUPD_BY
					)
				END
		
			END
				SET @P_GROUPS = RIGHT(@P_GROUPS, LEN(@P_GROUPS) - @V_Pos)
				SET @V_Pos = CHARINDEX(',', @P_GROUPS, 1)
			SELECT @P_ErrorCode = @@error
		END
	SELECT @P_ErrorCode = @@error
	IF @P_ErrorCode <> 0 GOTO ABEND
COMMIT TRAN
	ABEND:
IF @P_ErrorCode <> 0
	BEGIN
		PRINT 'Yikes!'
		ROLLBACK TRAN
	END
