CREATE PROCEDURE [ZFP_GET_ACCT_SECURITY](
	@P_ACCT AS VARCHAR(50),
	@P_SE_SEQ_ID AS INT,
	@P_ErrorCode int OUTPUT
) AS

SELECT
	ZFC_SECURITY_RLS.[NAME] AS Roles
FROM
	ZFC_ACCTS,
	ZFC_SECURITY_ACCTS_RLS,
	ZFC_SECURITY_RLS_SE,
	ZFC_SECURITY_RLS
WHERE
	ZFC_ACCTS.ACCT = @P_ACCT
	AND ZFC_SECURITY_ACCTS_RLS.ACCT_SEQ_ID = ZFC_ACCTS.ACCT_SEQ_ID
	AND ZFC_SECURITY_ACCTS_RLS.RLS_SE_SEQ_ID = ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.SE_SEQ_ID IN (SELECT SE_SEQ_ID FROM dbo.ZFF_GET_SE_PARENTS(1,@P_SE_SEQ_ID))
	AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID
UNION
SELECT
	ZFC_SECURITY_RLS.[NAME] AS Roles
FROM
	ZFC_ACCTS,
	ZFC_SECURITY_ACCTS_GRPS,
	ZFC_SECURITY_GRPS_SE,
	ZFC_SECURITY_GRPS_RLS,
	ZFC_SECURITY_RLS_SE,
	ZFC_SECURITY_RLS
WHERE
	ZFC_ACCTS.ACCT = @P_ACCT
	AND ZFC_SECURITY_ACCTS_GRPS.ACCT_SEQ_ID = ZFC_ACCTS.ACCT_SEQ_ID
	AND ZFC_SECURITY_GRPS_SE.SE_SEQ_ID IN (SELECT SE_SEQ_ID FROM dbo.ZFF_GET_SE_PARENTS(1,@P_SE_SEQ_ID))
	AND ZFC_SECURITY_GRPS_SE.GRPS_SE_SEQ_ID = ZFC_SECURITY_GRPS_RLS.GRPS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.RLS_SE_SEQ_ID = ZFC_SECURITY_GRPS_RLS.RLS_SE_SEQ_ID
	AND ZFC_SECURITY_RLS_SE.ROLE_SEQ_ID = ZFC_SECURITY_RLS.ROLE_SEQ_ID

SELECT @P_ErrorCode=@@ERROR
