CREATE PROCEDURE [ZFP_GET_WORK_FLOW]
	@P_PRIMARY_KEY INT,
	@P_ErrorCode int OUTPUT
AS
SET NOCOUNT ON
-- SELECT A ROW  from the table.
SELECT
	WORK_FLOW_ID,
	ORDER_ID,
	WORK_FLOW_NAME,
	FUNCTION_SEQ_ID
FROM 	ZOP_WORK_FLOWS
WHERE
	WORK_FLOW_ID = @P_PRIMARY_KEY
ORDER BY
	ORDER_ID
-- Get the Error Code for the statement just executed.
SELECT @P_ErrorCode=@@ERROR
