
CREATE PROCEDURE [ZFP_DEL_GRP_ACCTS](
	@P_GROUP_SEQ_ID AS INT,
	@P_SE_SEQ_ID AS INT,
	@P_ADDUPD_BY AS	INT
)
AS
	DELETE
		ZFC_SECURITY_ACCTS_GRPS
	WHERE
		GRPS_SE_SEQ_ID IN (
			SELECT 
				GRPS_SE_SEQ_ID 
			FROM 
				ZFC_SECURITY_GRPS_SE 
			WHERE 
				GROUP_SEQ_ID = @P_GROUP_SEQ_ID 
				AND SE_SEQ_ID = @P_SE_SEQ_ID
		)

