'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddEditNVPDetails

    '''<summary>
    '''frmAddEditNVPDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmAddEditNVPDetails As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdnNVP_SEQ_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNVP_SEQ_ID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnNVP_SEQ_DET_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNVP_SEQ_DET_ID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''reqTxtValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqTxtValue As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtText As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''reqTxtText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqTxtText As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtSortOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSortOrder As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dropStatusID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropStatusID As Global.System.Web.UI.WebControls.DropDownList
End Class
