'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''ModulesSecurity class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class ModulesSecurity

	'''<summary>
	'''ctlViewRoles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctlViewRoles As Global.ApplicationBase.Common.CustomWebControls.ListPicker

	'''<summary>
	'''ctlAddRoles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctlAddRoles As Global.ApplicationBase.Common.CustomWebControls.ListPicker

	'''<summary>
	'''ctlEditRoles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctlEditRoles As Global.ApplicationBase.Common.CustomWebControls.ListPicker

	'''<summary>
	'''ctlDeleteRoles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctlDeleteRoles As Global.ApplicationBase.Common.CustomWebControls.ListPicker
End Class
