'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''LeftHandModuleHeader class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class LeftHandModuleHeader

	'''<summary>
	'''trLeftHandModuleHeader control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents trLeftHandModuleHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''tdEdit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tdEdit As Global.System.Web.UI.HtmlControls.HtmlTableCell

	'''<summary>
	'''anchorEditPage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents anchorEditPage As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''tdClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tdClose As Global.System.Web.UI.HtmlControls.HtmlTableCell

	'''<summary>
	'''anchorClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents anchorClose As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
