ALTER TABLE [ZGWSecurity].[Functions]
    ADD CONSTRAINT [PK_Functions] PRIMARY KEY CLUSTERED ([Function_SeqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

