version: '3.8'
# docker pull mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
# docker pull mcr.microsoft.com/devcontainers/dotnet:8.0
# docker pull mcr.microsoft.com/mssql/server:2022-latest
# docker pull node:20.9.0
# How To Remove Docker Images, Containers, and Volumes		
# 	https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
# Build the containers from docker-compose.yml
#   docker-compose up --build -d
# Start a Docker container with a bash shell
#   docker exec -it growthware-code bash

services:
  # growthware-angular:
  #   build:
  #     context: .devcontainer/angular
  #   container_name: growthware-angular
  #   command: sleep infinity
  #   image: growthware-angular:4.0.1.0   # Tag specified here
  #   volumes:
  #     - ./Web.Angular:/workspace:cached
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - growthware-api
  #   networks:
  #     - growthware-backend
  
  # growthware-api:
  #   build:
  #     context: .devcontainer/dotnet-api
  #   container_name: growthware-api
  #   image: growthware-api:4.0.1.0   # Tag specified here
  #   command: sleep infinity
  #   volumes:
  #     - .:/workspace:cached
  #   ports:
  #     - "5000:5000"
  #     - "5001:5001"
  #   depends_on:
  #     - growthware-db
  #   networks:
  #     - growthware-backend

  growthware-code:
    build:
      context: .devcontainer/code
    container_name: growthware-code
    command: sleep infinity
    image: growthware-code:4.0.1.0   # Tag specified here
    volumes:
      - ./:/workspace:cached
    depends_on:
      - growthware-db
    networks:
      - growthware-backend

  # The service name "growthware-db" becomes the "server=" in your connection string
  growthware-db:
    build:
      context: .devcontainer/sql-server
    container_name: growthware-db
    volumes:
      - growthware-db-volume:/var/opt/mssql
    ports:
      - "1433:1433"
    image: growthware-db:4.0.1.0  # Tag specified here
    networks:
      - growthware-backend

networks:
  growthware-backend:

volumes:
  growthware-db-volume:
    driver: local
