'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''ChangeColors class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class ChangeColors

	'''<summary>
	'''Radio1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Radio1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

	'''<summary>
	'''blueImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents blueImage As Global.System.Web.UI.HtmlControls.HtmlImage

	'''<summary>
	'''Radio2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Radio2 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

	'''<summary>
	'''greenImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents greenImage As Global.System.Web.UI.HtmlControls.HtmlImage

	'''<summary>
	'''Radio3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Radio3 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

	'''<summary>
	'''yellowImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents yellowImage As Global.System.Web.UI.HtmlControls.HtmlImage

	'''<summary>
	'''Radio4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Radio4 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

	'''<summary>
	'''purpleImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents purpleImage As Global.System.Web.UI.HtmlControls.HtmlImage

	'''<summary>
	'''Radio5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Radio5 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

	'''<summary>
	'''redImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents redImage As Global.System.Web.UI.HtmlControls.HtmlImage

	'''<summary>
	'''trSubmit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents trSubmit As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
