'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''AddEditDropDownDetails class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class AddEditDropDownDetails

	'''<summary>
	'''dropDropDowns control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dropDropDowns As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''dgResults control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dgResults As Global.System.Web.UI.WebControls.DataGrid

	'''<summary>
	'''txtCode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCode As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''txtValue control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtValue As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''btnAddDropDownValue control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAddDropDownValue As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''Message control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Message As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
