'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''AddEditDropDown class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class AddEditDropDown

	'''<summary>
	'''NavTrail1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents NavTrail1 As Global.ApplicationBase.Common.CustomWebControls.NavTrail

	'''<summary>
	'''Tabstrip1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Tabstrip1 As Global.ApplicationBase.Common.CustomWebControls.TabStrip

	'''<summary>
	'''bottomTabStrip control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents bottomTabStrip As Global.System.Web.UI.HtmlControls.HtmlTableCell

	'''<summary>
	'''pnlGeneral control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlGeneral As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DropDownGeneral control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DropDownGeneral As Global.ApplicationBase.DropDownGeneral

	'''<summary>
	'''pnlSecurity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlSecurity As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''RolesControl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RolesControl As Global.ApplicationBase.RolesControl

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''Navtrail2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Navtrail2 As Global.ApplicationBase.Common.CustomWebControls.NavTrail
End Class
