<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="System.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework\GrowthWare.Framework.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

</Project>
