ALTER TABLE [dbo].[ZFC_FUNCTIONS]
    ADD CONSTRAINT [FK_ZFC_FUNCTIONS_ZFC_FUNCTIONS] FOREIGN KEY ([PARENT_FUNCTION_SEQ_ID]) REFERENCES [dbo].[ZFC_FUNCTIONS] ([FUNCTION_SEQ_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

