ALTER TABLE [dbo].[ZFC_SECURITY_ACCTS_GRPS]
    ADD CONSTRAINT [FK_ZFC_ACCTS_GRPS_ZFC_ACCTS] FOREIGN KEY ([ACCT_SEQ_ID]) REFERENCES [dbo].[ZFC_ACCTS] ([ACCT_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

