ALTER TABLE [dbo].[ZFO_WORK_FLOWS]
    ADD CONSTRAINT [FK_ZFO_WORK_FLOWS_ZFC_SYSTEM_STATUS] FOREIGN KEY ([STATUS_SEQ_ID]) REFERENCES [dbo].[ZFC_SYSTEM_STATUS] ([STATUS_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

