ALTER TABLE [dbo].[ZFC_SECURITY_ACCTS_RLS]
    ADD CONSTRAINT [FK_ZFC_ACCTS_RLS_ZFC_ACCTS] FOREIGN KEY ([ACCT_SEQ_ID]) REFERENCES [dbo].[ZFC_ACCTS] ([ACCT_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

