ALTER TABLE [dbo].[ZFO_DIRECTORIES]
    ADD CONSTRAINT [FK_ZFO_DIRECTORIES_ZFC_FUNCTIONS1] FOREIGN KEY ([FUNCTION_SEQ_ID]) REFERENCES [dbo].[ZFC_FUNCTIONS] ([FUNCTION_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

