ALTER TABLE [dbo].[ZFC_SECURITY_GRPS_GRPS]
    ADD CONSTRAINT [FK_ZFC_GRPS_GRPS_ZFC_GRPS] FOREIGN KEY ([GROUP_SEQ_ID]) REFERENCES [dbo].[ZFC_SECURITY_GRPS] ([GROUP_SEQ_ID]) ON DELETE CASCADE ON UPDATE CASCADE;

