ALTER TABLE [dbo].[ZOP_STATES]
    ADD CONSTRAINT [PK_ZOP_STATES] PRIMARY KEY CLUSTERED ([STATE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

