ALTER TABLE [dbo].[ZFC_FUNCTION_TYPES]
    ADD CONSTRAINT [PK_ZFC_FUNCTION_TYPES] PRIMARY KEY CLUSTERED ([FUNCTION_TYPE_SEQ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

