ALTER TABLE [dbo].[ZFC_INFORMATION]
    ADD CONSTRAINT [PK_ZFC_INFORMATION] PRIMARY KEY CLUSTERED ([Information_SEQ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

