ALTER TABLE [dbo].[ZFO_DIRECTORIES]
    ADD CONSTRAINT [PK_ZFO_DIRECTORIES] PRIMARY KEY CLUSTERED ([FUNCTION_SEQ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

