ALTER TABLE [dbo].[ZFC_NAVIGATION_TYPES]
    ADD CONSTRAINT [PK_ZFC_NAVIGATION_TYPES] PRIMARY KEY CLUSTERED ([NVP_SEQ_DET_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

