ALTER TABLE [dbo].[ZFC_NOTIFICATIONS]
    ADD CONSTRAINT [PK_ZFC_NOTIFICATIONS] PRIMARY KEY CLUSTERED ([NOTIFICATION_SEQ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

