ALTER TABLE [dbo].[ZFC_PERMISSIONS]
    ADD CONSTRAINT [PK_ZFC_PERMISSIONS] PRIMARY KEY CLUSTERED ([NVP_SEQ_DET_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

