ALTER TABLE [dbo].[ZFC_ACCTS]
    ADD CONSTRAINT [UK_ZFC_ACCTS] UNIQUE NONCLUSTERED ([ACCT] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

