ALTER TABLE [dbo].[ZFC_SECURITY_RLS_SE]
    ADD CONSTRAINT [UK_ZFC_RLS_SE] UNIQUE NONCLUSTERED ([ROLE_SEQ_ID] ASC, [SE_SEQ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

