ALTER TABLE [dbo].[ZFC_NAVIGATION_TYPES]
    ADD CONSTRAINT [UK_ZFC_NAVIGATION_TYPES] UNIQUE NONCLUSTERED ([NVP_DET_VALUE] ASC, [NVP_DET_TEXT] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

