ALTER TABLE [dbo].[ZFC_FUNCTIONS]
    ADD CONSTRAINT [UK_ZFC_FUNCTIONS] UNIQUE NONCLUSTERED ([ACTION] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

