CREATE TABLE [dbo].[ZFO_ACCT_CHOICES] (
    [ACCT]             VARCHAR (128)  NOT NULL,
    [SE_SEQ_ID]        VARCHAR (50)   NULL,
    [SE_NAME]          VARCHAR (256)  NULL,
    [BACK_COLOR]       VARCHAR (15)   NULL,
    [LEFT_COLOR]       VARCHAR (15)   NULL,
    [HEAD_COLOR]       VARCHAR (15)   NULL,
    [SUB_HEAD_COLOR]   VARCHAR (15)   NULL,
    [COLOR_SCHEME]     VARCHAR (15)   NULL,
    [FAVORIATE_ACTION] VARCHAR (50)   NULL,
    [THIN_ACTIONS]     VARCHAR (1000) NULL,
    [WIDE_ACTIONS]     VARCHAR (1000) NULL,
    [RECORDS_PER_PAGE] VARCHAR (9)    NULL
);

