'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''ApplicationInformation class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class ApplicationInformation

	'''<summary>
	'''Label1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblAppName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAppName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Label2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblEnvironment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblEnvironment As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Label3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblVersion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblVersion As Global.System.Web.UI.WebControls.Label
End Class
