'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''PageHeaderControl class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class PageHeaderControl

	'''<summary>
	'''AppImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AppImage As Global.System.Web.UI.WebControls.Image

	'''<summary>
	'''ApplicationInformation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ApplicationInformation As Global.ApplicationBase.ApplicationInformation

	'''<summary>
	'''ClientLogonInformation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ClientLogonInformation As Global.ApplicationBase.ClientLogonInformation

	'''<summary>
	'''tdClientSecurityInformation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tdClientSecurityInformation As Global.System.Web.UI.HtmlControls.HtmlTableCell

	'''<summary>
	'''LineMenu1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LineMenu1 As Global.ApplicationBase.LineMenu

	'''<summary>
	'''HierarchalMenu control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HierarchalMenu As Global.ApplicationBase.HierarchalMenu
End Class
