'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''AddEditMessages class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class AddEditMessages

	'''<summary>
	'''ClientMSG control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ClientMSG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''dropMessageNames control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dropMessageNames As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblMessageDescription control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessageDescription As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtMessageTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMessageTitle As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtMessageBody control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMessageBody As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnEdit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnEdit As Global.System.Web.UI.WebControls.Button
End Class
