-- Upgrade Create all the tables/views, Stored procedures, Functions, etc. (DDL);
-- All command must end in a semicolon, the semicolon will be removed before being executed.;
-- SET ECHO ON;
-- SET VERIFY ON;
-- SET FEEDBACK ON;
-- SET DEFINE ON;
-- CLEAR SCREEN;
-- set serveroutput on

ALTER SESSION SET CONTAINER = YourDatabaseName;

-- Create users (schemas) and grant necessary privileges
CREATE USER ZGWSystem IDENTIFIED BY realyitsMe;
CREATE USER ZGWOptional IDENTIFIED BY realyitsMe;
CREATE USER ZGWSecurity IDENTIFIED BY realyitsMe;
CREATE USER ZGWCOREWEB IDENTIFIED BY ZGWCOREWEB;
COMMIT;

GRANT ALL PRIVILEGES TO ZGWSystem;
GRANT ALL PRIVILEGES to ZGWOptional;
GRANT ALL PRIVILEGES to ZGWSecurity;
GRANT ALL PRIVILEGES to ZGWCOREWEB;
COMMIT;

ALTER SESSION SET current_schema=ZGWSystem;
CREATE TABLE Database_Information (
  Database_InformationSeqId NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE ,
  Version VARCHAR2(50 CHAR) NOT NULL,
  Enable_Inheritance NUMBER(10,0) NOT NULL,
  Added_By NUMBER(10,0) NOT NULL,
  Added_Date DATE NOT NULL,
  Updated_By NUMBER(10,0),
  Updated_Date DATE
);

ALTER TABLE Database_Information MODIFY (Added_By DEFAULT (1));
-- PROMPT Creating Primary Key Constraint PK_ZGWSystem_Database_Information on table Database_Information ... 
ALTER TABLE Database_Information
ADD CONSTRAINT PK_ZGWSystem_Database_Information PRIMARY KEY
(
  Database_InformationSeqId
)
ENABLE;

COMMIT;

GRANT ALL ON Database_Information TO ZGWCoreWeb,ZGWOptional,ZGWSecurity;
