-- Upgrade Create all the tables-views, Stored procedures, Functions, etc. (DDL)/
-- All command must end in a forward slash, the forward slash will be removed before being executed./
-- SET ECHO ON/
-- SET VERIFY ON;
-- SET FEEDBACK ON/
-- SET DEFINE ON/
-- CLEAR SCREEN/
-- set serveroutput on/

ALTER SESSION SET CONTAINER = YourDatabaseName/

-- Create users (schemas) and grant necessary privileges/
CREATE USER ZGWSystem IDENTIFIED BY YourPasswordHere/
CREATE USER ZGWOptional IDENTIFIED BY YourPasswordHere/
CREATE USER ZGWSecurity IDENTIFIED BY YourPasswordHere/
CREATE USER ZGWCoreWeb IDENTIFIED BY YourPasswordHere/
COMMIT/

GRANT ALL PRIVILEGES TO ZGWSystem/
GRANT ALL PRIVILEGES to ZGWOptional/
GRANT ALL PRIVILEGES to ZGWSecurity/
GRANT ALL PRIVILEGES to ZGWCoreWeb/
COMMIT/

ALTER SESSION SET current_schema=ZGWSystem/
CREATE TABLE Database_Information (
  Database_InformationSeqId NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE ,
  Version VARCHAR2(50 CHAR) NOT NULL,
  Enable_Inheritance NUMBER(10,0) NOT NULL,
  Added_By NUMBER(10,0) NOT NULL,
  Added_Date DATE NOT NULL,
  Updated_By NUMBER(10,0),
  Updated_Date DATE
)/

ALTER TABLE Database_Information MODIFY (Added_By DEFAULT (1))/
-- PROMPT Creating Primary Key Constraint PK_ZGWSystem_Database_Information on table Database_Information ... 
ALTER TABLE Database_Information
ADD CONSTRAINT PK_ZGWSystem_Database_Information PRIMARY KEY
(
  Database_InformationSeqId
)
ENABLE/

COMMIT/

GRANT ALL ON Database_Information TO ZGWSystem, ZGWOptional, ZGWSecurity, ZGWCoreWeb/
COMMIT/

CREATE OR REPLACE FUNCTION ZGWSystem.Set_DataBase_Information 
--
--Usage:
--	DECLARE 
--		@P_Database_InformationSeqId INT = 1,
--		@P_Version VARCHAR(15) = '3',
--		@P_Enable_Inheritance INT = 1,
--		@P_Added_Updated_By INT = 1,
--		@P_Primary_Key int,
--		@P_Debug INT = 1
--
--	exec ZGWSystem.Set_DataBase_Information
--		@P_Database_InformationSeqId,
--		@P_Version,
--		@P_Enable_Inheritance,
--		@P_Added_Updated_By,
--		@P_Primary_Key,
--		@P_Debug
--
-- =============================================
-- Author:		Michael Regan
-- Create date: 07\28\2011
-- Description:	Inserts or updates a record from ZGWSystem.Set_DataBase_Information
--	given the Database_InformationSeqId
-- =============================================

(
  p_Database_InformationSeqId IN NUMBER,
  p_Version IN VARCHAR2,
  p_Enable_Inheritance IN NUMBER,
  p_Added_Updated_By IN NUMBER,
  p_Primary_Key OUT NUMBER,
  p_Debug IN NUMBER DEFAULT 0 
)
RETURN NUMBER
AS

BEGIN

   DECLARE
      v_V_Now DATE := SYSDATE;
      v_temp NUMBER(1, 0) := 0;
   
   BEGIN
      BEGIN
         SELECT 1 INTO v_temp
           FROM DUAL
          WHERE ( SELECT COUNT(*)  
                  FROM ZGWSystem.Database_Information  ) = 0;
      EXCEPTION
         WHEN OTHERS THEN
            NULL;
      END;
         
      IF v_temp = 1 THEN
       
      BEGIN
         -- INSERT
         INSERT INTO ZGWSystem.Database_Information
           ( Version, Enable_Inheritance, Added_By, Added_Date )
           VALUES ( p_Version, p_Enable_Inheritance, p_Added_Updated_By, v_V_Now );
         p_Primary_Key := utils.getidentity ;-- Get the IDENTITY value for the row just inserted.
      
      END;
      ELSE -- UPDATE
      BEGIN
         UPDATE ZGWSystem.Database_Information
            SET Version = p_Version,
                Enable_Inheritance = p_Enable_Inheritance,
                Updated_By = p_Added_Updated_By,
                Updated_Date = v_V_Now
          WHERE  Database_InformationSeqId = p_Database_InformationSeqId;
         p_Primary_Key := p_Database_InformationSeqId ;
      
      END;
      END IF;
   
   END;
   -- END IF
   RETURN 0;

-- EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;
/

GRANT ALL ON Set_DataBase_Information TO ZGWSystem, ZGWOptional, ZGWSecurity, ZGWCoreWeb/
